# AIRBNB PRICE FORECASTER BY KAREN BLANCO

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as mplot
%matplotlib inline 

In [2]:
import os
print(os.getcwd())

d:\AI Bootcamp Github\bnb_forecaster_ML\notebooks


El data sets presenta problemas de lectura por lo que para evitar esto chequeamos si hay extra commas, espacios indeseados dentro de celdas, quotes sin cerrar,etc. Podemos aplicar un sep o delimiter=';'

## 1. Análisis previo a preparación de datos

Vamos a conocer un poco la data y sus tipos. Nos muestra que hay 14780 entradas y 89 columnas.

In [3]:

bnb_data = pd.read_csv("./data/airbnb-listings-extract.csv",sep=';', decimal='.', encoding='utf-8')
print("bnb_data Shape:", bnb_data .shape)
pd.set_option('display.max_columns', None)
bnb_data .head(5)



bnb_data Shape: (14780, 89)


ID                            Listing Url       Scrape ID  \
0  11210388  https://www.airbnb.com/rooms/11210388  20170306202425   
1  17471131  https://www.airbnb.com/rooms/17471131  20170407214050   
2  17584891  https://www.airbnb.com/rooms/17584891  20170407214050   
3   5398030   https://www.airbnb.com/rooms/5398030  20170407214050   
4  18104606  https://www.airbnb.com/rooms/18104606  20170407214050   

  Last Scraped                                 Name  \
0   2017-03-07       The Loft-Full Bath-Deck w/View   
1   2017-04-08           Claris I, Friendly Rentals   
2   2017-04-08  Style Terrace Red, Friendly Rentals   
3   2017-04-08    Picasso Suite 1.4 Paseo de Gracia   
4   2017-04-08       Smart City Centre Apartment II   

                                             Summary  \
0  Loft in the Hill country 12-15 minutes directl...   
1  This apartment has: 1 double bed, 1 double sof...   
2  This apartment has: 1 double bed, 1 double sof...   
3  Live like a local in Barcelona's most chic dis...   
4  Unique apartment in vibrant neighborhoods, car...   

                                               Space  \
0  This loft has a spectacular view of the hills ...   
1  This apartment has: 1 double bed, 1 double sof...   
2  This apartment has: 1 double bed, 1 double sof...   
3  You wake up to the sun rising over Barcelona's...   
4  License: HUTB-005313 Charming apartment, locat...   

                                         Description Experiences Offered  \
0  Loft in the Hill country 12-15 minutes directl...                none   
1  This apartment has: 1 double bed, 1 double sof...                none   
2  This apartment has: 1 double bed, 1 double sof...                none   
3  Live like a local in Barcelona's most chic dis...                none   
4  Unique apartment in vibrant neighborhoods, car...                none   

                               Neighborhood Overview  \
0  This neighborhood is located in the hills west...   
1  Plaza   Cataluña Catalonia Square is the large...   
2  Plaza   Cataluña Catalonia Square is the large...   
3  We're right in the heart of the chic L'Eixampl...   
4                                                NaN   

                                               Notes  \
0  The loft is located on a gated property.  Ther...   
1                                                NaN   
2                                                NaN   
3                          Local permit: HUTB-006794   
4                                                NaN   

                                             Transit  \
0  There is no public transportation from this lo...   
1  Ideal to discover the city either on foot or b...   
2  Ideal to discover the city either on foot or b...   
3  Whatever it is you came to see in Barcelona, I...   
4                                                NaN   

                                              Access  \
0  The loft is entirely private to the guest as i...   
1  Travellers will have access to the entire apar...   
2  Travellers will have access to the entire apar...   
3  This property features keyless entry, making i...   
4                                                NaN   

                                         Interaction  \
0  My wife and I live on the property so we would...   
1  We will be more than happy to help you with an...   
2  We will be more than happy to help you with an...   
3  I'm an Aussie who's lived in Barcelona for alm...   
4                                                NaN   

                                         House Rules  \
0  The loft is entirely private but is adjacent t...   
1  CHECK-IN Week Days: The check-in and key colle...   
2  CHECK-IN Week Days: The check-in and key colle...   
3  Welcome to Barcelona! This will be your home n...   
4                                                NaN   

                                       Thumbnail Url  \
0  https://a0.muscache.com/im/pictures/c351a9b5-

In [4]:
# Mostrar las categorías únicas de 'Property Type'
unique_property_type_cleaned = bnb_data['Property Type'].unique()
print("Categorías únicas de Property Type:", unique_property_type_cleaned)

# Mostrar el número total de categorías únicas
total_unique_property_types = len(unique_property_type_cleaned)
print("\nNúmero total de categorías únicas en 'Property Type':", total_unique_property_types)

# Contar el total de registros por cada categoría en 'Property Type'
property_type_counts = bnb_data['Property Type'].value_counts()
print("\nTotal de registros por cada categoría de Property Type:\n", property_type_counts)


Categorías únicas de Property Type: ['Loft' 'Apartment' 'House' 'Condominium' 'Camper/RV' 'Other' 'Dorm'
 'Bed & Breakfast' 'Tent' 'Boat' 'Guesthouse' 'Villa' 'Hostel' 'Townhouse'
 'Chalet' 'Serviced apartment' 'Bungalow' 'Boutique hotel' 'Guest suite'
 'Casa particular' 'Timeshare' 'Earth House']

Número total de categorías únicas en 'Property Type': 22

Total de registros por cada categoría de Property Type:
 Property Type
Apartment             11962
House                  1368
Condominium             363
Bed & Breakfast         353
Loft                    305
Other                   225
Dorm                     44
Guesthouse               42
Chalet                   26
Villa                    19
Townhouse                17
Hostel                   16
Serviced apartment       13
Boutique hotel            6
Boat                      4
Camper/RV                 4
Guest suite               3
Casa particular           3
Earth House               3
Bungalow                  2
Tent       

In [5]:
# Filtrar registros sin amenities y contar la cantidad de registros sin amenities
no_amenities_df = bnb_data[bnb_data['Amenities'].isna()]
num_no_amenities = no_amenities_df.shape[0]

# Mostrar el número de registros sin amenities
print(f"Número de registros sin amenities: {num_no_amenities}")

# Mostrar la columna amenities para estos registros
no_amenities_df[['Amenities']]


Número de registros sin amenities: 170


Amenities
80          NaN
94          NaN
121         NaN
150         NaN
237         NaN
...         ...
14634       NaN
14660       NaN
14664       NaN
14690       NaN
14724       NaN

[170 rows x 1 columns]

In [6]:
# Ver los tipos únicos de amenities presentes en el dataset
unique_amenities = bnb_data['Amenities'].str.split(',', expand=True).stack().str.strip().unique()

# Imprimir la cantidad de amenities únicas
print("Número de amenities únicas:", len(unique_amenities))

# Opcionalmente, puedes ver la lista de amenities únicas
unique_amenities

Número de amenities únicas: 105


array(['TV', 'Cable TV', 'Internet', 'Wireless Internet',
       'Air conditioning', 'Pool', 'Free parking on premises', 'Heating',
       'Family/kid friendly', 'Smoke detector',
       'Carbon monoxide detector', 'Fire extinguisher', 'Essentials',
       'Shampoo', 'Lock on bedroom door', '24-hour check-in', 'Hangers',
       'Hair dryer', 'Iron', 'Laptop friendly workspace', 'Self Check-In',
       'Doorman Entry', 'Private entrance', 'Elevator in building',
       'Washer', 'Wheelchair accessible', 'Kitchen', 'Doorman',
       'Breakfast', 'Buzzer/wireless intercom', 'Lockbox', 'Safety card',
       'Smoking allowed', 'First aid kit', 'Indoor fireplace', 'Dryer',
       'translation missing: en.hosting_amenity_49',
       'translation missing: en.hosting_amenity_50', 'Hot tub',
       'Pets allowed', 'Keypad', 'Private living room',
       'Pets live on this property', 'Cat(s)', 'Dog(s)',
       'Suitable for events', 'Smartlock', 'Gym',
       'Free parking on street', 'Other pet(

In [7]:
# Ver los tipos únicos de amenities presentes en el dataset
unique_amenities = bnb_data['Amenities'].str.split(',', expand=True).stack().str.strip().unique()
print(unique_amenities)

# Mostrar el número total de categorías únicas
total_unique_amenities = len(unique_amenities)
print("\nNúmero total de categorías únicas en 'Amenities':", total_unique_amenities)

['TV' 'Cable TV' 'Internet' 'Wireless Internet' 'Air conditioning' 'Pool'
 'Free parking on premises' 'Heating' 'Family/kid friendly'
 'Smoke detector' 'Carbon monoxide detector' 'Fire extinguisher'
 'Essentials' 'Shampoo' 'Lock on bedroom door' '24-hour check-in'
 'Hangers' 'Hair dryer' 'Iron' 'Laptop friendly workspace' 'Self Check-In'
 'Doorman Entry' 'Private entrance' 'Elevator in building' 'Washer'
 'Wheelchair accessible' 'Kitchen' 'Doorman' 'Breakfast'
 'Buzzer/wireless intercom' 'Lockbox' 'Safety card' 'Smoking allowed'
 'First aid kit' 'Indoor fireplace' 'Dryer'
 'translation missing: en.hosting_amenity_49'
 'translation missing: en.hosting_amenity_50' 'Hot tub' 'Pets allowed'
 'Keypad' 'Private living room' 'Pets live on this property' 'Cat(s)'
 'Dog(s)' 'Suitable for events' 'Smartlock' 'Gym' 'Free parking on street'
 'Other pet(s)' 'Bathtub' 'Washer / Dryer' 'Crib' 'Room-darkening shades'
 'Buzzer/Wireless Intercom' 'Smoke Detector' 'Carbon Monoxide Detector'
 'First Aid K

In [8]:
print("Columns in the DataFrame:")
print(bnb_data .columns)


Columns in the DataFrame:
Index(['ID', 'Listing Url', 'Scrape ID', 'Last Scraped', 'Name', 'Summary',
       'Space', 'Description', 'Experiences Offered', 'Neighborhood Overview',
       'Notes', 'Transit', 'Access', 'Interaction', 'House Rules',
       'Thumbnail Url', 'Medium Url', 'Picture Url', 'XL Picture Url',
       'Host ID', 'Host URL', 'Host Name', 'Host Since', 'Host Location',
       'Host About', 'Host Response Time', 'Host Response Rate',
       'Host Acceptance Rate', 'Host Thumbnail Url', 'Host Picture Url',
       'Host Neighbourhood', 'Host Listings Count',
       'Host Total Listings Count', 'Host Verifications', 'Street',
       'Neighbourhood', 'Neighbourhood Cleansed',
       'Neighbourhood Group Cleansed', 'City', 'State', 'Zipcode', 'Market',
       'Smart Location', 'Country Code', 'Country', 'Latitude', 'Longitude',
       'Property Type', 'Room Type', 'Accommodates', 'Bathrooms', 'Bedrooms',
       'Beds', 'Bed Type', 'Amenities', 'Square Feet', 'Price', 'We

In [9]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

bnb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14780 entries, 0 to 14779
Data columns (total 89 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   ID                              14780 non-null  int64  
 1   Listing Url                     14780 non-null  object 
 2   Scrape ID                       14780 non-null  int64  
 3   Last Scraped                    14780 non-null  object 
 4   Name                            14779 non-null  object 
 5   Summary                         14189 non-null  object 
 6   Space                           10888 non-null  object 
 7   Description                     14774 non-null  object 
 8   Experiences Offered             14780 non-null  object 
 9   Neighborhood Overview           9134 non-null   object 
 10  Notes                           5644 non-null   object 
 11  Transit                         9066 non-null   object 
 12  Access                          

In [10]:
#Hacemos un .describe para hacer una analisis rapido de la distribucion central y tendencias.

bnb_data.describe()

ID     Scrape ID       Host ID  Host Response Rate  \
count  1.478000e+04  1.478000e+04  1.478000e+04        12881.000000   
mean   1.028089e+07  2.017037e+13  3.608080e+07           94.823461   
std    5.564829e+06  5.667971e+08  3.425360e+07           15.215988   
min    1.862800e+04  2.016010e+13  1.745300e+04            0.000000   
25%    5.554732e+06  2.017041e+13  6.787360e+06          100.000000   
50%    1.133492e+07  2.017041e+13  2.464875e+07          100.000000   
75%    1.532631e+07  2.017041e+13  5.432919e+07          100.000000   
max    1.910969e+07  2.017062e+13  1.247534e+08          100.000000   

       Host Listings Count  Host Total Listings Count      Latitude  \
count         14777.000000               14777.000000  14780.000000   
mean             12.513636                  12.513636     40.497626   
std              34.090223                  34.090223      4.641387   
min               0.000000                   0.000000    -37.851182   
25%               1.000000                   1.000000     40.409726   
50%               2.000000                   2.000000     40.419466   
75%               6.000000                   6.000000     40.430916   
max             519.000000                 519.000000     55.966912   

          Longitude  Accommodates     Bathrooms      Bedrooms         Beds  \
count  14780.000000  14780.000000  14725.000000  14755.000000  14731.00000   
mean      -3.858041      3.277808      1.281732      1.343816      2.04426   
std       14.123146      2.097291      0.658517      0.900078      1.61277   
min     -123.131344      1.000000      0.000000      0.000000      1.00000   
25%       -3.707604      2.000000      1.000000      1.000000      1.00000   
50%       -3.700785      3.000000      1.000000      1.000000      2.00000   
75%       -3.684057      4.000000      1.000000      2.000000      2.00000   
max      153.371427     16.000000      8.000000     10.000000     16.00000   

       Square Feet         Price  Weekly Price  Monthly Price  \
count   598.000000  14763.000000   3590.000000    3561.000000   
mean    390.456522     73.561471    376.937883    1426.125246   
std     637.134930     72.062050    195.701043    1246.403853   
min       0.000000      9.000000     70.000000     250.000000   
25%       0.000000     34.000000    215.000000     720.000000   
50%      98.500000     55.000000    350.000000    1200.000000   
75%     646.000000     86.000000    500.000000    1725.000000   
max    6997.000000    999.000000    999.000000   25000.000000   

       Security Deposit  Cleaning Fee  Guests Included  Extra People  \
count       6256.000000   8687.000000     14780.000000  14780.000000   
mean         189.226822     31.805341         1.589986      7.690460   
std          115.151070     30.878599         1.182550     12.971352   
min            0.000000      0.000000         0.000000      0.000000   
25%          100.000000     15.000000         1.000000      0.000000   
50%          150.000000     25.000000         1.000000      0.000000   
75%          200.000000     40.000000         2.000000     15.000000   
max          990.000000    662.000000        16.000000    500.000000   

       Minimum Nights  Maximum Nights  Availability 30  Availability 60  \
count    14780.000000    14780.000000     14780.000000     14780.000000   
mean         3.050474      945.168742         8.954736        22.996211   
std         12.266517     8439.321218         9.333252        19.731371   
min          1.000000        1.000000         0.000000         0.000000   
25%          1.000000      365.000000         0.000000         4.000000   
50%          2.000000     1125.000000         6.000000        20.000000   
75%          3.000000     1125.000000        14.000000        38.000000   
max       1125.000000  1000000.000000        30.000000        60.000000   

       Availability 90  Availability 365  Number of Reviews  \
count     14780.000000      14780.000000       14780.000000 

In [11]:
#Chequeamos si hay nulls para indentificarlos.

bnb_data.isnull().sum()

ID                                    0
Listing Url                           0
Scrape ID                             0
Last Scraped                          0
Name                                  1
Summary                             591
Space                              3892
Description                           6
Experiences Offered                   0
Neighborhood Overview              5646
Notes                              9136
Transit                            5714
Access                             6462
Interaction                        6554
House Rules                        5161
Thumbnail Url                      2820
Medium Url                         2820
Picture Url                          19
XL Picture Url                     2820
Host ID                               0
Host URL                              0
Host Name                             3
Host Since                            3
Host Location                        43
Host About                         5241


Chequeamos el % de Missing Values que tiene cada item para poder eliminar las que tengan un % alto y no sirvan apra nuestro modelo.
Has availability, Jurisdiction Names, License, Host Aceptance Rate no son relevantes para precio y peuden descartarse.

In [12]:
bnb_data.isnull().sum()/bnb_data.shape[0]*100

ID                                 0.000000
Listing Url                        0.000000
Scrape ID                          0.000000
Last Scraped                       0.000000
Name                               0.006766
Summary                            3.998647
Space                             26.332882
Description                        0.040595
Experiences Offered                0.000000
Neighborhood Overview             38.200271
Notes                             61.813261
Transit                           38.660352
Access                            43.721245
Interaction                       44.343708
House Rules                       34.918809
Thumbnail Url                     19.079838
Medium Url                        19.079838
Picture Url                        0.128552
XL Picture Url                    19.079838
Host ID                            0.000000
Host URL                           0.000000
Host Name                          0.020298
Host Since                      

In [13]:
#Chequear duplicados

bnb_data.duplicated().sum()

0

In [14]:
bnb_data.select_dtypes(include="object").columns


Index(['Listing Url', 'Last Scraped', 'Name', 'Summary', 'Space',
       'Description', 'Experiences Offered', 'Neighborhood Overview', 'Notes',
       'Transit', 'Access', 'Interaction', 'House Rules', 'Thumbnail Url',
       'Medium Url', 'Picture Url', 'XL Picture Url', 'Host URL', 'Host Name',
       'Host Since', 'Host Location', 'Host About', 'Host Response Time',
       'Host Acceptance Rate', 'Host Thumbnail Url', 'Host Picture Url',
       'Host Neighbourhood', 'Host Verifications', 'Street', 'Neighbourhood',
       'Neighbourhood Cleansed', 'Neighbourhood Group Cleansed', 'City',
       'State', 'Zipcode', 'Market', 'Smart Location', 'Country Code',
       'Country', 'Property Type', 'Room Type', 'Bed Type', 'Amenities',
       'Calendar Updated', 'Has Availability', 'Calendar last Scraped',
       'First Review', 'Last Review', 'License', 'Jurisdiction Names',
       'Cancellation Policy', 'Geolocation', 'Features'],
      dtype='object')

### *Eliminamos features que no seran relevantes para el label precio desde un inicio:*


❌**ID, Listing Url, Scrape ID, Host ID, Host URL, Picture URLs, Thumbnail URLs.:** son identificadores únicos y no aportan valor al modelo. No tienen ninguna relación directa con el precio del Airbnb.

❌**Last Scraped, Calendar Last Scraped, Host Since:** Estas son fechas relacionadas con el scraping o actividad temporal que no contribuyen directamente a la predicción del precio.

❌**Host Name, Host Thumbnail Url, Host Picture Url:** Información del host que no es relevante para determinar el precio de la propiedad.

❌**Name, Space, Description, Neighborhood Overview, Notes, Transit, Access, Interaction, House Rules:** Estas columnas son principalmente textuales, utiliaremos NLP con las mas relevantes en la predicción del precio como summary y description.

❌**Experiences Offered:** Esta columna tiene muy poco valor porque el campo parece ser estático en la mayoría de los casos.

❌**Medium Url, XL Picture Url, Features:** No contribuyen a la predicción de precios.

❌**Host About:** Esta columna es información descriptiva del host, sin influencia directa en el precio.

❌**Host Response Time, Host Response Rate, Host Acceptance Rate:** Aunque podrían ser relevantes para la satisfacción del cliente, la influencia en el precio es indirecta y no fundamental para una primera aproximación.

❌**License, Jurisdiction Names:** Información de licencias locales que no tiene impacto en el precio.

❌**Calendar Updated:** Información sobre cuándo se actualizó el calendario que no tiene impacto directo en el precio.

❌**Has Availability:** Esta columna tiene muy pocos datos completos (solo 12 no nulos), por lo que no aporta al modelo.

❌**Geolocation, Street:** ya tenemos columna de latitude y longitude y con zipcode, neighborhud tenemos info exacta de localizacion, evitamos redundancia

❌**Thumbnail Url, Medium Url, XL Picture Url, Picture Url:** Enlaces a imágenes que no contribuyen a la predicción.

❌**Calculated host listings count, Host Listings Count:** tienen bastante correlacion con Total Host listings count, eliminamos 2 para evitar multicolinealidad.

In [15]:
# Features a eliminar
columns_to_drop = [
    'ID', 'Listing Url', 'Scrape ID', 'Last Scraped', 'Name', 'Space', 'Experiences Offered',
    'Neighborhood Overview', 'Notes', 'Transit', 'Access', 'Interaction', 'House Rules', 'Thumbnail Url', 
    'Medium Url', 'Picture Url', 'XL Picture Url', 'Host ID', 'Host URL', 'Host Name', 'Host Since', 'Host Location',
    'Host About', 'Host Response Time', 'Host Response Rate', 'Host Acceptance Rate', 'Host Thumbnail Url',
    'Host Picture Url', 'Calendar Updated', 'Has Availability', 'Geolocation', 'License', 'Jurisdiction Names', 'Features','Host Neighbourhood',
    'Calculated host listings count','Host Listings Count','Calendar last Scraped','Host Verifications', 'Street'
]

bnb_data_cleaned = bnb_data.drop(columns=columns_to_drop)


In [16]:
# Imprimir cada columna 
for column in sorted(bnb_data_cleaned.columns):
    print(column)


Accommodates
Amenities
Availability 30
Availability 365
Availability 60
Availability 90
Bathrooms
Bed Type
Bedrooms
Beds
Cancellation Policy
City
Cleaning Fee
Country
Country Code
Description
Extra People
First Review
Guests Included
Host Total Listings Count
Last Review
Latitude
Longitude
Market
Maximum Nights
Minimum Nights
Monthly Price
Neighbourhood
Neighbourhood Cleansed
Neighbourhood Group Cleansed
Number of Reviews
Price
Property Type
Review Scores Accuracy
Review Scores Checkin
Review Scores Cleanliness
Review Scores Communication
Review Scores Location
Review Scores Rating
Review Scores Value
Reviews per Month
Room Type
Security Deposit
Smart Location
Square Feet
State
Summary
Weekly Price
Zipcode


In [17]:
bnb_data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14780 entries, 0 to 14779
Data columns (total 49 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Summary                       14189 non-null  object 
 1   Description                   14774 non-null  object 
 2   Host Total Listings Count     14777 non-null  float64
 3   Neighbourhood                 9551 non-null   object 
 4   Neighbourhood Cleansed        14780 non-null  object 
 5   Neighbourhood Group Cleansed  13760 non-null  object 
 6   City                          14774 non-null  object 
 7   State                         14636 non-null  object 
 8   Zipcode                       14274 non-null  object 
 9   Market                        14723 non-null  object 
 10  Smart Location                14780 non-null  object 
 11  Country Code                  14780 non-null  object 
 12  Country                       14779 non-null  object 
 13  L

In [18]:
bnb_data_cleaned.isnull().sum()

Summary                           591
Description                         6
Host Total Listings Count           3
Neighbourhood                    5229
Neighbourhood Cleansed              0
Neighbourhood Group Cleansed     1020
City                                6
State                             144
Zipcode                           506
Market                             57
Smart Location                      0
Country Code                        0
Country                             1
Latitude                            0
Longitude                           0
Property Type                       0
Room Type                           0
Accommodates                        0
Bathrooms                          55
Bedrooms                           25
Beds                               49
Bed Type                            0
Amenities                         170
Square Feet                     14182
Price                              17
Weekly Price                    11190
Monthly Pric

In [19]:
#Para limpieza mas profunda antes de dividir datos podemos asegurarnos de convertir todo a minúsculas, evitar espacio y caracteres especiales.
import re

# Convertir los nombres de las columnas a minúsculas y eliminar caracteres especiales
bnb_data_cleaned.columns = bnb_data_cleaned.columns.str.lower().str.strip().str.replace(r'\s+', '_', regex=True).str.replace(r'[^a-z0-9_]', '', regex=True)

# Convertir los valores de las celdas de texto a minúsculas y eliminar caracteres especiales, PERO manteniendo comas dentro de las celdas
bnb_data_cleaned = bnb_data_cleaned.apply(lambda x: x.str.lower().str.strip().apply(lambda y: re.sub(r'[^a-z0-9,\s]', '', y) if pd.notna(y) else y) if x.dtype == "object" else x)

bnb_data_cleaned.head()


summary  \
0  loft in the hill country 1215 minutes directly...   
1  this apartment has 1 double bed, 1 double sofa...   
2  this apartment has 1 double bed, 1 double sofa...   
3  live like a local in barcelonas most chic dist...   
4  unique apartment in vibrant neighborhoods, car...   

                                         description  \
0  loft in the hill country 1215 minutes directly...   
1  this apartment has 1 double bed, 1 double sofa...   
2  this apartment has 1 double bed, 1 double sofa...   
3  live like a local in barcelonas most chic dist...   
4  unique apartment in vibrant neighborhoods, car...   

   host_total_listings_count                  neighbourhood  \
0                        1.0                            NaN   
1                      162.0                            NaN   
2                      162.0                            NaN   
3                       27.0                            NaN   
4                      207.0  lantiga esquerra de leixample   

          neighbourhood_cleansed neighbourhood_group_cleansed       city  \
0                          78733                          NaN     austin   
1          la dreta de leixample                     eixample  barcelona   
2          la dreta de leixample                     eixample  barcelona   
3          la dreta de leixample                     eixample  barcelona   
4  lantiga esquerra de leixample                     eixample  barcelona   

       state zipcode     market    smart_location country_code        country  \
0         tx   78733     austin        austin, tx           us  united states   
1  barcelona   08010  barcelona  barcelona, spain           es          spain   
2  barcelona   08008  barcelona  barcelona, spain           es          spain   
3  barcelona   08009  barcelona  barcelona, spain           es          spain   
4  catalunya   08036  barcelona  barcelona, spain           es          spain   

    latitude  longitude property_type       room_type  accommodates  \
0  30.337361 -97.863277          loft  entire homeapt             2   
1  41.389683   2.172625     apartment  entire homeapt             4   
2  41.393035   2.162173     apartment  entire homeapt             4   
3  41.396967   2.167418     apartment  entire homeapt             8   
4  41.388685   2.155150     apartment  entire homeapt             5   

   bathrooms  bedrooms  beds  bed_type  \
0        1.0       1.0   1.0  real bed   
1        1.0       1.0   1.0  real bed   
2        1.0       1.0   1.0  real bed   
3        2.0       3.0   4.0  real bed   
4        1.0       2.0   2.0  real bed   

                                           amenities  square_feet  price  \
0  tv,cable tv,internet,wireless internet,air con...          NaN   58.0   
1  wireless internet,air conditioning,elevator in...          NaN   70.0   
2  wireless internet,air conditioning,elevator in...          NaN   70.0   
3  tv,internet,wireless internet,air conditioning...          NaN  229.0   
4  tv,wireless internet,air conditioning,kitchen,...          NaN  149.0   

   weekly_price  monthly_price  security_deposit  cleaning_fee  \
0           NaN            NaN             100.0           NaN   
1           NaN            NaN             200.0          40.0   
2           NaN            NaN             200.0          60.0   
3           NaN            NaN             250.0          79.0   
4           NaN            NaN               NaN          55.0   

   guests_included  extra_people  minimum_nights  maximum_nights  \
0                1             0               2            1125   
1                2            44               1            1125   
2                2            42               1            1125   
3                2            39               2            1125   
4                1             0               2            1125   

   availability_30  availability_60  availability_90  availability_365  \
0               10             

In [20]:
# Mostrar las categorías únicas de 'Property Type'
unique_property_type_cleaned = bnb_data_cleaned['property_type'].unique()
print("Categorías únicas de Property Type:", unique_property_type_cleaned)

# Mostrar el número total de categorías únicas
total_unique_property_types = len(unique_property_type_cleaned)
print("\nNúmero total de categorías únicas en 'Property Type':", total_unique_property_types)

# Contar el total de registros por cada categoría en 'Property Type'
property_type_counts = bnb_data_cleaned['property_type'].value_counts()
print("\nTotal de registros por cada categoría de Property Type:\n", property_type_counts)

Categorías únicas de Property Type: ['loft' 'apartment' 'house' 'condominium' 'camperrv' 'other' 'dorm'
 'bed  breakfast' 'tent' 'boat' 'guesthouse' 'villa' 'hostel' 'townhouse'
 'chalet' 'serviced apartment' 'bungalow' 'boutique hotel' 'guest suite'
 'casa particular' 'timeshare' 'earth house']

Número total de categorías únicas en 'Property Type': 22

Total de registros por cada categoría de Property Type:
 property_type
apartment             11962
house                  1368
condominium             363
bed  breakfast          353
loft                    305
other                   225
dorm                     44
guesthouse               42
chalet                   26
villa                    19
townhouse                17
hostel                   16
serviced apartment       13
boutique hotel            6
boat                      4
camperrv                  4
guest suite               3
casa particular           3
earth house               3
bungalow                  2
tent         

In [21]:
# Ver los tipos únicos de amenities presentes en el dataset
unique_amenities = bnb_data_cleaned['amenities'].str.split(',', expand=True).stack().str.strip().unique()
print(unique_amenities)

# Mostrar el número total de categorías únicas
total_unique_amenities = len(unique_amenities)
print("\nNúmero total de categorías únicas en 'amenities':", total_unique_amenities)

['tv' 'cable tv' 'internet' 'wireless internet' 'air conditioning' 'pool'
 'free parking on premises' 'heating' 'familykid friendly'
 'smoke detector' 'carbon monoxide detector' 'fire extinguisher'
 'essentials' 'shampoo' 'lock on bedroom door' '24hour checkin' 'hangers'
 'hair dryer' 'iron' 'laptop friendly workspace' 'self checkin'
 'doorman entry' 'private entrance' 'elevator in building' 'washer'
 'wheelchair accessible' 'kitchen' 'doorman' 'breakfast'
 'buzzerwireless intercom' 'lockbox' 'safety card' 'smoking allowed'
 'first aid kit' 'indoor fireplace' 'dryer'
 'translation missing enhostingamenity49'
 'translation missing enhostingamenity50' 'hot tub' 'pets allowed'
 'keypad' 'private living room' 'pets live on this property' 'cats' 'dogs'
 'suitable for events' 'smartlock' 'gym' 'free parking on street'
 'other pets' 'bathtub' 'washer  dryer' 'crib' 'roomdarkening shades'
 'window guards' 'game console' 'hot water' 'bed linens'
 'extra pillows and blankets' 'microwave' 'coffee

In [22]:
# Guardar el dataset limpio antes de dividir
bnb_data_cleaned.to_csv('./data/airbnb-listings-cleaned.csv', sep=';', decimal='.', index=False, encoding='utf-8')


## 1. Carga de datos y división train/test después de análisis previo


In [23]:
#Lo haré con método train_test_split

from sklearn.model_selection import train_test_split

bnb_data_cleaned = pd.read_csv("./data/airbnb-listings-cleaned.csv", sep=';', decimal='.', encoding='utf-8')
train, test = train_test_split(bnb_data_cleaned, test_size=0.2, shuffle=True, random_state=0)

print(f'Dimensiones del dataset de training: {train.shape}')
print(f'Dimensiones del dataset de test: {test.shape}')

# Guardar
train.to_csv('./data/airbnb-listings-cleaned_train.csv', sep=';', decimal='.', index=False, encoding='utf-8')
test.to_csv('./data/airbnb-listings-cleaned_test.csv', sep=';', decimal='.', index=False, encoding='utf-8')

# A partir de este momento cargamos el dataset de train y trabajamos ÚNICAMENTE con él. Los llamare df_bnb_train y df_bnb_test

df_bnb_train = pd.read_csv('./data/airbnb-listings-cleaned_train.csv',sep=';', decimal='.', encoding='utf-8')
df_bnb_train.head().T

Dimensiones del dataset de training: (11824, 49)
Dimensiones del dataset de test: (2956, 49)


0  \
summary                       piso recin reformado cmoda habitacin con bao, ...   
description                   piso recin reformado cmoda habitacin con bao, ...   
host_total_listings_count                                                   2.0   
neighbourhood                                                          jernimos   
neighbourhood_cleansed                                                 jernimos   
neighbourhood_group_cleansed                                             retiro   
city                                                                     madrid   
state                                                       comunidad de madrid   
zipcode                                                                   28014   
market                                                                   madrid   
smart_location                                                    madrid, spain   
country_code                                                                 es   
country                                                                   spain   
latitude                                                              40.407732   
longitude                                                             -3.684819   
property_type                                                         apartment   
room_type                                                        entire homeapt   
accommodates                                                                  4   
bathrooms                                                                   1.0   
bedrooms                                                                    1.0   
beds                                                                        2.0   
bed_type                                                               real bed   
amenities                     tv,internet,wireless internet,air conditioning...   
square_feet                                                                 NaN   
price                                                                      60.0   
weekly_price                                                              550.0   
monthly_price                                                            1250.0   
security_deposit                                                            NaN   
cleaning_fee                                                               25.0   
guests_included                                                               1   
extra_people                                                                  0   
minimum_nights                                                                2   
maximum_nights                                                             1125   
availability_30                                                               9   
availability_60                                                              32   
availability_90                                                              52   
availability_365                                                            117   
number_of_reviews                                                            12   
first_review                                                         20150426.0   
last_review                                                          20170228.0   
review_scores_rating                                                       95.0   
review_scores_accuracy                                                      9.0   
review_scores_cleanliness                                                  10.0   
review_scores_checkin                                                      10.0   
review_scores_communication                                                10.0   
review_scores_location                                                     10.0   
review_scores_value                                                         9.0   
cancellation_policy                                                    moderate   
reviews_per

In [24]:
# Ver los tipos únicos de amenities presentes en el dataset
unique_amenities = df_bnb_train['amenities'].str.split(',', expand=True).stack().str.strip().unique()

# Imprimir la cantidad de amenities únicas
print("Número de amenities únicas:", len(unique_amenities))

# Opcionalmente, puedes ver la lista de amenities únicas
unique_amenities


Número de amenities únicas: 82


array(['tv', 'internet', 'wireless internet', 'air conditioning',
       'kitchen', 'doorman', 'elevator in building',
       'buzzerwireless intercom', 'heating', 'familykid friendly',
       'washer', 'essentials', 'hangers', 'smoke detector',
       'carbon monoxide detector', 'shampoo', '24hour checkin',
       'hair dryer', 'iron', 'laptop friendly workspace',
       'wheelchair accessible', 'pool', 'free parking on premises',
       'breakfast', 'suitable for events', 'first aid kit', 'safety card',
       'fire extinguisher', 'lock on bedroom door', 'smoking allowed',
       'cable tv', 'translation missing enhostingamenity50',
       'translation missing enhostingamenity49', 'private entrance',
       'dryer', 'pets allowed', 'hot tub', 'indoor fireplace', 'gym',
       'private living room', 'pets live on this property', 'dogs',
       'bathtub', 'self checkin', 'doorman entry', 'cats', 'lockbox',
       'babysitter recommendations', 'roomdarkening shades', 'other pets',
     

## 2. Análisis exploratorio

## 2b. Imputar Nulls

In [25]:
df_bnb_train.isnull().sum()

summary                           473
description                         7
host_total_listings_count           3
neighbourhood                    4159
neighbourhood_cleansed              1
neighbourhood_group_cleansed      818
city                               49
state                             165
zipcode                           399
market                             44
smart_location                      0
country_code                        0
country                             1
latitude                            0
longitude                           0
property_type                       0
room_type                           0
accommodates                        0
bathrooms                          44
bedrooms                           20
beds                               37
bed_type                            0
amenities                         141
square_feet                     11350
price                              15
weekly_price                     8943
monthly_pric

In [26]:
#NULLS EN SQUARE_FEET Y CONVERTIR A square_meters imputando con media

# Reemplazar valores de 0 en square_feet por NaN en el conjunto de entrenamiento
df_bnb_train['square_feet'] = df_bnb_train['square_feet'].replace(0, np.nan)

# Imputar valores nulos en square_feet por mediana agrupada
df_bnb_train['square_feet'] = df_bnb_train.groupby(['property_type', 'bedrooms', 'accommodates'])['square_feet'].transform(lambda x: x.fillna(x.median()))

# Si aún hay nulos, imputar por la mediana global en square_feet
df_bnb_train['square_feet'] = df_bnb_train['square_feet'].fillna(df_bnb_train['square_feet'].median())

# Convertir square_feet a square_meters después de la imputación
df_bnb_train['square_meters'] = df_bnb_train['square_feet'] * 0.092903



In [27]:
# Eliminar square_feet de df_bnb_train para evitar duplicación
df_bnb_train = df_bnb_train.drop(columns=['square_feet'])

In [28]:
df_bnb_train[['square_meters']].isnull().sum()

square_meters    0
dtype: int64

In [29]:
print(df_bnb_train.columns)


Index(['summary', 'description', 'host_total_listings_count', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'city',
       'state', 'zipcode', 'market', 'smart_location', 'country_code',
       'country', 'latitude', 'longitude', 'property_type', 'room_type',
       'accommodates', 'bathrooms', 'bedrooms', 'beds', 'bed_type',
       'amenities', 'price', 'weekly_price', 'monthly_price',
       'security_deposit', 'cleaning_fee', 'guests_included', 'extra_people',
       'minimum_nights', 'maximum_nights', 'availability_30',
       'availability_60', 'availability_90', 'availability_365',
       'number_of_reviews', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'cancellation_policy', 'reviews_per_month',
       'square_meters'],
      dtype='object')


In [30]:
# Código para mostrar solo las columnas 'summary' y 'description' del dataframe
df_bnb_train[['summary', 'description']].head(10)


summary  \
0  piso recin reformado cmoda habitacin con bao, ...   
1  lugares de inters plaza mayor, plaza del sol, ...   
2  , la casa tiene 5 habitaciones, 180m2 totalmen...   
3  this stunning and amazig room is covered with ...   
4                                                NaN   
5  se trata de una habitacin en piso muy luminoso...   
6  apartment 2 minute walking to sol, mayor squar...   
7  estupendo piso de gran tamao, totalmente refor...   
8  this gorgeous sea view apartment in the pictur...   
9  located in one of the best neighbourhoods in m...   

                                         description  
0  piso recin reformado cmoda habitacin con bao, ...  
1  lugares de inters plaza mayor, plaza del sol, ...  
2  , la casa tiene 5 habitaciones, 180m2 totalmen...  
3  this stunning and amazig room is covered with ...  
4  we are a young couple david spain and ana colo...  
5  se trata de una habitacin en piso muy luminoso...  
6  apartment 2 minute walking to sol, mayor squar...  
7  estupendo piso de gran tamao, totalmente refor...  
8  this gorgeous sea view apartment in the pictur...  
9  located in one of the best neighbourhoods in m...

In [31]:
#NULLS en summary y description, imputando con genericos e info del mismo registro

import pandas as pd

print("Valores nulos en summary:", df_bnb_train['summary'].isnull().sum())
print("Valores nulos en description:", df_bnb_train['description'].isnull().sum())

# Imputar valores nulos en 'summary' con el valor de 'description' del mismo registro, y viceversa.
df_bnb_train['summary'] = df_bnb_train.apply(lambda row: row['description'] if pd.isna(row['summary']) and pd.notna(row['description']) else row['summary'], axis=1)
df_bnb_train['description'] = df_bnb_train.apply(lambda row: row['summary'] if pd.isna(row['description']) and pd.notna(row['summary']) else row['description'], axis=1)

# Verificar si quedan valores nulos en 'summary' o 'description' y mostrar en pantalla
print("Valores nulos despues de imputacion entre valores de mismo registro:")
print("Summary nulos:", df_bnb_train['summary'].isnull().sum())
print("Description nulos:", df_bnb_train['description'].isnull().sum())

# Imputar valores genéricos en 'summary' y 'description' si aún hay nulos.
df_bnb_train['summary'] = df_bnb_train['summary'].fillna('No summary available')
df_bnb_train['description'] = df_bnb_train['description'].fillna('No description provided')


# Verificar si quedan valores nulos en 'summary_length' o 'description_length' y mostrar en pantalla
print("Valores nulos en 'summary' y 'description' después de la imputación y conversión:")
print("Summary Length nulos:", df_bnb_train['summary'].isnull().sum())
print("Description Length nulos:", df_bnb_train['description'].isnull().sum())


Valores nulos en summary: 473
Valores nulos en description: 7
Valores nulos despues de imputacion entre valores de mismo registro:
Summary nulos: 6
Description nulos: 6
Valores nulos en 'summary' y 'description' después de la imputación y conversión:
Summary Length nulos: 0
Description Length nulos: 0


In [32]:
duplicates = df_bnb_train[df_bnb_train['summary'] == df_bnb_train['description']]
print(f"Número de duplicados exactos entre 'summary' y 'description': {len(duplicates)}")


Número de duplicados exactos entre 'summary' y 'description': 3102


In [33]:
duplicate_percentage = (len(duplicates) / len(df_bnb_train)) * 100
print(f"Porcentaje de duplicados exactos: {duplicate_percentage:.2f}%")


Porcentaje de duplicados exactos: 26.23%


In [34]:
df_bnb_train.isnull().sum()

summary                            0
description                        0
host_total_listings_count          3
neighbourhood                   4159
neighbourhood_cleansed             1
neighbourhood_group_cleansed     818
city                              49
state                            165
zipcode                          399
market                            44
smart_location                     0
country_code                       0
country                            1
latitude                           0
longitude                          0
property_type                      0
room_type                          0
accommodates                       0
bathrooms                         44
bedrooms                          20
beds                              37
bed_type                           0
amenities                        141
price                             15
weekly_price                    8943
monthly_price                   8955
security_deposit                6772
c

### ***Nulos en bathrooms, bedrooms y beds***

Estas caracteristicas son importantes y debemos imputarlas correctamente con los mejores datos.

**Estrategia de imputación**

KNN podría proporcionar una imputación más precisa para bedrooms, bathrooms y beds, ya que estas características están influenciadas por varias otras como property_type, square_meters, y accommodates. La imputación con KNN aprovecharía las similitudes entre registros para llenar los valores de una forma más cercana a los valores reales.

1.Se seleccionan las columnas que tienen influencia en bathrooms, bedrooms, y beds, incluyendo características como property_type, square_meters, y accommodates.

2.Las columnas categóricas son convertidas a variables dummy, para que KNN pueda manejar los valores.

3.Se utiliza StandardScaler para escalar los datos. Esto es importante porque KNN utiliza distancias para encontrar vecinos, y las características en diferentes escalas pueden influir en la imputación. Escalar asegura que todas las características tengan la misma importancia al calcular la distancia.

4.Se utiliza el imputador KNN para rellenar los valores faltantes de las columnas (bathrooms, bedrooms, beds).

5.Conversión de datos imputados a enteros: Debido a que KNN puede devolver valores decimales, se realiza una conversión a enteros (round().astype(int)) para bedrooms y beds.

In [35]:
df_bnb_train[['property_type', 'bedrooms', 'bathrooms', 'beds', 'room_type', 'bed_type']].isnull().sum()


property_type     0
bedrooms         20
bathrooms        44
beds             37
room_type         0
bed_type          0
dtype: int64

In [36]:
df_bnb_train[['property_type', 'bedrooms', 'bathrooms', 'beds', 'room_type', 'bed_type']].dtypes

property_type     object
bedrooms         float64
bathrooms        float64
beds             float64
room_type         object
bed_type          object
dtype: object

In [37]:
from sklearn.impute import KNNImputer

# Seleccionar las columnas relevantes para la imputación
columns_to_impute = ['bathrooms', 'bedrooms', 'beds']
features_for_knn = ['property_type', 'square_meters', 'accommodates', 'room_type', 'bed_type'] + columns_to_impute

# Crear una copia del dataset para trabajar en la imputación
knn_data = df_bnb_train[features_for_knn].copy()

# Convertir columnas categóricas a códigos numéricos temporales
for col in ['property_type', 'room_type', 'bed_type']:
    knn_data[col] = knn_data[col].astype('category').cat.codes

# Aplicar KNN Imputer
knn_imputer = KNNImputer(n_neighbors=5)
knn_data_imputed = knn_imputer.fit_transform(knn_data)

# Convertir los datos imputados de vuelta a un DataFrame
knn_data_imputed_df = pd.DataFrame(knn_data_imputed, columns=knn_data.columns)

# Actualizar las columnas imputadas en el dataset original
for col in columns_to_impute:
    df_bnb_train[col] = knn_data_imputed_df[col].round().astype(int)


In [38]:
df_bnb_train[['property_type', 'bedrooms', 'bathrooms', 'beds', 'room_type', 'bed_type']].isnull().sum()

property_type    0
bedrooms         0
bathrooms        0
beds             0
room_type        0
bed_type         0
dtype: int64

### *Tratando mas valores Nulos*
**Columnas con más del 50% de valores nulos:**

weekly_price (8,943 nulos), monthly_price (8,955 nulos), security_deposit (6,772 nulos), y cleaning_fee (4,850 nulos).
square_feet: imputar la mediana agrupando por property_type y bedrooms para obtener un valor más representativo.
weekly_price y monthly_price: imputar utilizando el precio diario (price) multiplicado por 7 o 30, respectivamente.
security_deposit y cleaning_fee: imputar la mediana agrupando por property_type. Para valores que aún estén nulos después, imputar con la mediana general.

**Columnas con Menos Valores Nulos:**

Por ejemplo, bathrooms (44 nulos), bedrooms (20 nulos), beds (37 nulos), price (15 nulos).
Para columnas numéricas con pocos valores nulos, se puede imputar con la mediana, ya que ayuda a mitigar el efecto de valores atípicos.
Para columnas categóricas como neighbourhood_cleansed (1 nulo), country (1 nulo), y city (49 nulos), se puede imputar con la moda (el valor más frecuente).


In [39]:
df_bnb_train[['weekly_price', 'monthly_price', 'security_deposit', 'cleaning_fee', 'room_type', 'bed_type']].isnull().sum()

weekly_price        8943
monthly_price       8955
security_deposit    6772
cleaning_fee        4850
room_type              0
bed_type               0
dtype: int64

In [40]:
# Análisis de correlación entre precios para validar relaciones
price_corr = df_bnb_train[['price', 'weekly_price', 'monthly_price']].corr()
print("Correlación entre price, weekly_price, y monthly_price:\n", price_corr)

Correlación entre price, weekly_price, y monthly_price:
                   price  weekly_price  monthly_price
price          1.000000      0.880469       0.827679
weekly_price   0.880469      1.000000       0.924147
monthly_price  0.827679      0.924147       1.000000


La correlación entre price y weekly_price (0.88) es alta y la correlación entre price y monthly_price (0.82) también es razonablemente alta, podemos imputar weekly_price como price * 7 y monthly_price como price * 30 en los valores faltantes.

In [41]:
import pandas as pd

# Imputación de 'weekly_price' y 'monthly_price' basado en el precio diario debido a la alta correlación
df_bnb_train['weekly_price'] = df_bnb_train['weekly_price'].fillna(df_bnb_train['price'] * 7)
df_bnb_train['monthly_price'] = df_bnb_train['monthly_price'].fillna(df_bnb_train['price'] * 30)

# Imputar cualquier valor restante en 'price', 'weekly_price', y 'monthly_price' con la mediana general
df_bnb_train['price'] = df_bnb_train['price'].fillna(df_bnb_train['price'].median())
df_bnb_train['weekly_price'] = df_bnb_train['weekly_price'].fillna(df_bnb_train['weekly_price'].median())
df_bnb_train['monthly_price'] = df_bnb_train['monthly_price'].fillna(df_bnb_train['monthly_price'].median())


In [42]:
# Mejor imputación para security_deposit y cleaning_fee con agrupación adicional
df_bnb_train['security_deposit'] = df_bnb_train.groupby(['property_type', 'bedrooms', 'smart_location'])['security_deposit'].transform(lambda x: x.fillna(x.median()))
df_bnb_train['cleaning_fee'] = df_bnb_train.groupby(['property_type', 'bedrooms', 'smart_location'])['cleaning_fee'].transform(lambda x: x.fillna(x.median()))

# Imputar cualquier valor restante en las columnas relevantes con la mediana general
cols_to_impute_with_median = ['square_meters', 'security_deposit', 'cleaning_fee']
for col in cols_to_impute_with_median:
    df_bnb_train[col] = df_bnb_train[col].fillna(df_bnb_train[col].median())

In [43]:
# Mostrar columnas con valores nulos y el total de cada una
print("Columnas con valores nulos y su total:")
print(df_bnb_train.isnull().sum()[df_bnb_train.isnull().sum() > 0])


Columnas con valores nulos y su total:
host_total_listings_count          3
neighbourhood                   4159
neighbourhood_cleansed             1
neighbourhood_group_cleansed     818
city                              49
state                            165
zipcode                          399
market                            44
country                            1
amenities                        141
first_review                    2539
last_review                     2540
review_scores_rating            2661
review_scores_accuracy          2681
review_scores_cleanliness       2676
review_scores_checkin           2688
review_scores_communication     2677
review_scores_location          2691
review_scores_value             2692
reviews_per_month               2539
dtype: int64


**Variables Relacionadas con Reviews:**

Muchas de las columnas de reseñas (review_scores) y reviews_per_month tienen varios valores nulos.
Imputar estos valores con 0 si el hecho de que no haya reseñas es representativo de que no han recibido ninguna (es decir, falta de reseñas = sin reseñas). Pero haremos primero comprobacion con mas columnas de reviews para saber si es cierto que un nulll es indicacion de falta de reseña.

**Dependencia entre las Reseñas:**

Verificamos si las filas que tienen valores nulos en review_scores_* también tienen valores nulos en number_of_reviews o reviews_per_month.
Si number_of_reviews es igual a cero y las columnas de review_scores_* tienen nulos, es una indicación de que no hay reseñas, y los valores nulos en las puntuaciones probablemente se deban a la falta de reviews.

**Agrupar las Propiedades con Valores Nulos en las Reseñas:**

Agrupa los valores nulos en las columnas de reseñas para verificar si tienen características comunes, como que number_of_reviews o days_since_last_review son cero o nulos.

In [44]:
# Verificar si los valores nulos en review_scores_* se deben a la falta de reseñas
review_cols = [
    'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness',
    'review_scores_checkin', 'review_scores_communication', 'review_scores_location',
    'review_scores_value', 'reviews_per_month'
]

# Comparar los nulos en las columnas de reviews con el número de reseñas
nulos_reviews = df_bnb_train[review_cols].isnull().sum()
sin_resenas = df_bnb_train[df_bnb_train['number_of_reviews'] == 0][review_cols].isnull().sum()

print("Valores nulos en las columnas de reviews:\n", nulos_reviews)
print("Valores nulos en las columnas de reviews cuando 'number_of_reviews' es 0:\n", sin_resenas)

# Analizar si las columnas reviews son nulas cuando no hay reseñas
propiedades_sin_resena = df_bnb_train[df_bnb_train['number_of_reviews'] == 0]
print("Total de propiedades sin reseña:", len(propiedades_sin_resena))
print("Valores nulos en las columnas de reviews para propiedades sin reseñas:\n", propiedades_sin_resena[review_cols].isnull().sum())


Valores nulos en las columnas de reviews:
 review_scores_rating           2661
review_scores_accuracy         2681
review_scores_cleanliness      2676
review_scores_checkin          2688
review_scores_communication    2677
review_scores_location         2691
review_scores_value            2692
reviews_per_month              2539
dtype: int64
Valores nulos en las columnas de reviews cuando 'number_of_reviews' es 0:
 review_scores_rating           2539
review_scores_accuracy         2539
review_scores_cleanliness      2539
review_scores_checkin          2539
review_scores_communication    2539
review_scores_location         2539
review_scores_value            2539
reviews_per_month              2539
dtype: int64
Total de propiedades sin reseña: 2539
Valores nulos en las columnas de reviews para propiedades sin reseñas:
 review_scores_rating           2539
review_scores_accuracy         2539
review_scores_cleanliness      2539
review_scores_checkin          2539
review_scores_communicatio

**Total de Propiedades sin Reseña:** 2539 propiedades no tienen ninguna reseña (number_of_reviews == 0).

**Valores Nulos en las Columnas de Reviews:** Coinciden exactamente con las propiedades sin reseña, lo cual indica que los nulos en estas columnas están relacionados con la falta de reseñas.

**Imputar con 0 para Columnas de Reviews y reviews_per_month:**
Para las propiedades que no tienen ninguna reseña (number_of_reviews == 0), es lógico imputar 0 en todas las columnas relacionadas con review_scores_* y reviews_per_month, ya que no se tiene información sobre la calidad.

In [45]:
# Definir columnas a imputar
review_score_cols = [
    'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 
    'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 
    'review_scores_value', 'reviews_per_month'
]

# Imputación por agrupación
for col in review_score_cols:
    # Imputar valores nulos con la mediana del grupo basado en 'property_type', 'room_type' y 'number_of_reviews'
    df_bnb_train[col] = df_bnb_train.groupby(['property_type', 'room_type', 'number_of_reviews'])[col].transform(lambda x: x.fillna(x.median()))

# Imputación con la mediana global para cualquier nulo restante
for col in review_score_cols:
    df_bnb_train[col] = df_bnb_train[col].fillna(df_bnb_train[col].median())

# Verificar que no haya nulos en las columnas de puntuación de reseñas y 'reviews_per_month'
print("Nulos restantes en las columnas de puntuación de reseñas y 'reviews_per_month' después de la imputación:")
print(df_bnb_train[review_score_cols].isnull().sum())


Nulos restantes en las columnas de puntuación de reseñas y 'reviews_per_month' después de la imputación:
review_scores_rating           0
review_scores_accuracy         0
review_scores_cleanliness      0
review_scores_checkin          0
review_scores_communication    0
review_scores_location         0
review_scores_value            0
reviews_per_month              0
dtype: int64


In [46]:
import pandas as pd
from datetime import datetime

# Convertir 'first_review' y 'last_review' a formato datetime
df_bnb_train['first_review'] = pd.to_datetime(df_bnb_train['first_review'])
df_bnb_train['last_review'] = pd.to_datetime(df_bnb_train['last_review'])

# Fecha de referencia para calcular los días
today = datetime.now()

# Convertir todas las fechas a días desde hoy
df_bnb_train['days_since_first_review'] = (today - df_bnb_train['first_review']).dt.days
df_bnb_train['days_since_last_review'] = (today - df_bnb_train['last_review']).dt.days

# Imputar todos los nulos directamente con la mediana global
df_bnb_train['days_since_first_review'] = df_bnb_train['days_since_first_review'].fillna(df_bnb_train['days_since_first_review'].median())
df_bnb_train['days_since_last_review'] = df_bnb_train['days_since_last_review'].fillna(df_bnb_train['days_since_last_review'].median())

# Calcular la duración de la actividad de reseñas en días
df_bnb_train['review_activity_duration'] = df_bnb_train['days_since_first_review'] - df_bnb_train['days_since_last_review']

# Eliminar las columnas originales de fecha ya que están transformadas
df_bnb_train.drop(columns=['first_review', 'last_review'], inplace=True)

# Verificar que no haya nulos en las nuevas columnas de días
print("Nulos en 'days_since_first_review', 'days_since_last_review' y 'review_activity_duration':")
print(df_bnb_train[['days_since_first_review', 'days_since_last_review', 'review_activity_duration']].isnull().sum())


Nulos en 'days_since_first_review', 'days_since_last_review' y 'review_activity_duration':
days_since_first_review     0
days_since_last_review      0
review_activity_duration    0
dtype: int64


In [47]:
print(df_bnb_train.isnull().sum()[df_bnb_train.isnull().sum() > 0])

host_total_listings_count          3
neighbourhood                   4159
neighbourhood_cleansed             1
neighbourhood_group_cleansed     818
city                              49
state                            165
zipcode                          399
market                            44
country                            1
amenities                        141
dtype: int64


In [48]:
unique_amenities = df_bnb_train['amenities'].unique()
unique_amenities 

array(['tv,internet,wireless internet,air conditioning,kitchen,doorman,elevator in building,buzzerwireless intercom,heating,familykid friendly,washer,essentials,hangers',
       'tv,internet,wireless internet,air conditioning,kitchen,elevator in building,heating,familykid friendly,washer,smoke detector,carbon monoxide detector,essentials,shampoo,24hour checkin,hangers,hair dryer,iron,laptop friendly workspace',
       'internet,wireless internet,wheelchair accessible,pool,kitchen,free parking on premises,doorman,breakfast,elevator in building,buzzerwireless intercom,heating,familykid friendly,suitable for events,washer,smoke detector,first aid kit,safety card,fire extinguisher,essentials,shampoo,lock on bedroom door,hangers,hair dryer,iron,laptop friendly workspace',
       ...,
       'tv,internet,wireless internet,kitchen,breakfast,elevator in building,buzzerwireless intercom,heating,familykid friendly,washer,first aid kit,safety card,essentials,shampoo,hangers,iron,laptop friendly w

In [49]:
import pandas as pd
from collections import Counter

# Asegurarse de que cada valor de 'amenities_list' sea una lista
df_bnb_train['amenities_list'] = df_bnb_train['amenities'].apply(
    lambda x: x.split(' ') if isinstance(x, str) else []
)

# Función para obtener los amenities más comunes por tipo de propiedad
def obtener_amenities_comunes(df, property_type, room_type):
    subset = df[(df['property_type'] == property_type) & (df['room_type'] == room_type)]
    amenities = sum(subset['amenities_list'].tolist(), [])  # Convertimos cada lista en 'amenities_list' en un solo conjunto de datos
    amenities_comunes = [item for item, _ in Counter(amenities).most_common(10)]  # Top 10 amenities
    return ' '.join(amenities_comunes)

# Imputación de nulos basada en property_type y room_type
df_bnb_train['amenities'] = df_bnb_train.apply(
    lambda row: obtener_amenities_comunes(df_bnb_train, row['property_type'], row['room_type']) 
    if pd.isna(row['amenities']) else row['amenities'], axis=1
)

# Eliminar columna temporal amenities_list si no es necesaria después de la imputación
df_bnb_train.drop(columns=['amenities_list'], inplace=True)

# Verificar si hay nulos en amenities después de la imputación
print("Nulos restantes en la columna 'amenities' después de la imputación:")
print(df_bnb_train['amenities'].isnull().sum())


Nulos restantes en la columna 'amenities' después de la imputación:
0


In [50]:
# Filtrar registros sin amenities y contar la cantidad de registros sin amenities
no_amenities_df = df_bnb_train[df_bnb_train['amenities'].isna()]
num_no_amenities = no_amenities_df.shape[0]

# Mostrar el número de registros sin amenities
print(f"Número de registros sin amenities: {num_no_amenities}")

# Mostrar la columna amenities para estos registros
no_amenities_df[['amenities']]

print(df_bnb_train[['amenities']].head(20))


Número de registros sin amenities: 0
                                            amenities
0   tv,internet,wireless internet,air conditioning...
1   tv,internet,wireless internet,air conditioning...
2   internet,wireless internet,wheelchair accessib...
3   wireless internet,kitchen,smoking allowed,heat...
4   tv,cable tv,internet,wireless internet,air con...
5   tv,internet,wireless internet,wheelchair acces...
6   tv,cable tv,internet,wireless internet,air con...
7   wireless internet,kitchen,smoking allowed,elev...
8   tv,internet,wireless internet,air conditioning...
9   tv,cable tv,internet,wireless internet,air con...
10  tv,wireless internet,kitchen,heating,familykid...
11  tv,wireless internet,air conditioning,kitchen,...
12  tv,wireless internet,air conditioning,kitchen,...
13  tv,internet,wireless internet,air conditioning...
14  tv,internet,wireless internet,air conditioning...
15  tv,wireless internet,air conditioning,kitchen,...
16  tv,wireless internet,kitchen,smoking allo

In [51]:
# Imputar 'host_total_listings_count' utilizando la mediana por 'property_type'
df_bnb_train['host_total_listings_count'] = df_bnb_train.groupby('property_type')['host_total_listings_count'].transform(lambda x: x.fillna(x.median()))

# Imputar cualquier valor restante con la mediana general si aún existen valores nulos
df_bnb_train['host_total_listings_count'] = df_bnb_train['host_total_listings_count'].fillna(df_bnb_train['host_total_listings_count'].median())

In [52]:
print(df_bnb_train.isnull().sum()[df_bnb_train.isnull().sum() > 0])


neighbourhood                   4159
neighbourhood_cleansed             1
neighbourhood_group_cleansed     818
city                              49
state                            165
zipcode                          399
market                            44
country                            1
dtype: int64


In [53]:
# tipos de datos de las columnas especificas
df_bnb_train.dtypes[['country', 'state', 'city', 'smart_location', 'zipcode', 
                     'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 
                     'neighbourhood', 'latitude', 'longitude']]


country                          object
state                            object
city                             object
smart_location                   object
zipcode                          object
neighbourhood_cleansed           object
neighbourhood_group_cleansed     object
neighbourhood                    object
latitude                        float64
longitude                       float64
dtype: object

**Variables de localización con Nulos**

Ahora las caraterisiticas que se relaciona con localizacion 'neighbourhood', 'city', 'state', 'zipcode' tienen varios nulos excepto latitude y longitude. Para asegurar que las imputaciones sean precisas y que la información sea consistente con la realidad geográfica utilizare KNN para imputación basada en distancia:

Con esto podré encontrar propiedades cercanas basadas en la proximidad espacial (latitude y longitude) y usar sus valores para imputar los datos faltantes.

Antes de aplicar KNN, es mejor realizar una agrupación preliminar considerando las coordenadas y alguna variable relacionada (si está disponible), para garantizar que no se imputen valores de áreas geográficas completamente diferentes.


In [54]:
df_bnb_train['zipcode'].unique()


array(['28014', '28012', '28025', '28015', '28005', '28013', '07181',
       '28006', '28028', '28009', '28008', '28026', '28004', '1040',
       '28003', '28002', '28033', '07011', '28017', '28045', '28020',
       '07579', '28046', nan, '75016', '28010', '28019', '28042', '28016',
       '28032', '28053', '28047', '28030', '28035', '28027', '00185',
       '28007', '28043', '28018', '28038', '28011', '2026', '98117',
       '90036', '28039', 'sm1 4sl', '75006', '08001', '07015', '1093 cp',
       '2', '28001', '10405', '07001', '07450', '10115', '28029', '07520',
       '91105', 'sw11 1hn', '07458', 'w3 9lw', '07320', '75017', '07609',
       '08009', '1700', '28041', '28037', '28024', '11215', '08015',
       '2010', '08003', '07530', '20002', '28054', 'eh7 4hj', '60657',
       '75018', 'sw3 5uw', '07140', '07010', '90046', '28022', '28040',
       '07170', '28034', '10035', '08011', 'd 8', '07680', '28050', 'v6z',
       '60622', '11206', '07550', '08005', '07002', '2000', '90013'

In [55]:
import pandas as pd
from sklearn.neighbors import NearestNeighbors

# 1. Imputar 'country' basado en 'country_code'
df_bnb_train['country'] = df_bnb_train['country'].fillna(df_bnb_train['country_code'].mode()[0])




In [56]:


# 2. Imputar 'state' basado en 'country', 'latitude', 'longitude' y 'zipcode'
# Primero verificamos si el 'state' es nulo y buscamos la mayoría de valores similares en 'latitude', 'longitude', y 'zipcode'
def imputar_state(row):
    if pd.isna(row['state']):
        subset = df_bnb_train[(df_bnb_train['country'] == row['country'])]
        if not subset.empty:
            return subset['state'].mode()[0]  # Usa el valor más frecuente en el mismo 'country'
    return row['state']

df_bnb_train['state'] = df_bnb_train.apply(imputar_state, axis=1)




In [57]:


# 3. Imputar 'market' basado en 'latitude', 'longitude', 'state' y 'country'
def imputar_market(row):
    if pd.isna(row['market']):
        subset = df_bnb_train[(df_bnb_train['country'] == row['country']) & (df_bnb_train['state'] == row['state'])]
        if not subset.empty:
            return subset['market'].mode()[0]
    return row['market']

df_bnb_train['market'] = df_bnb_train.apply(imputar_market, axis=1)




In [58]:
# 6. Imputar 'city' usando 'state', 'market', 'latitude', 'longitude'
def imputar_city(row):
    if pd.isna(row['city']):
        subset = df_bnb_train[(df_bnb_train['state'] == row['state']) & (df_bnb_train['market'] == row['market'])]
        if not subset.empty:
            return subset['city'].mode()[0]
    return row['city']

df_bnb_train['city'] = df_bnb_train.apply(imputar_city, axis=1)



In [59]:
from sklearn.neighbors import KNeighborsClassifier

# Convertir 'zipcode' a cadena para que funcione con KNN
df_bnb_train['zipcode'] = df_bnb_train['zipcode'].astype(str)

# Crear un subset con filas donde 'zipcode' no es nulo para entrenar el modelo
df_with_zipcode = df_bnb_train[df_bnb_train['zipcode'].notna()]

# Definir el clasificador KNN y las características de ubicación
knn = KNeighborsClassifier(n_neighbors=5)
location_features = ['latitude', 'longitude']

# Entrenar el modelo solo con registros que tienen 'zipcode' conocidos
knn.fit(df_with_zipcode[location_features], df_with_zipcode['zipcode'])

# Predecir 'zipcode' solo si hay filas con valores nulos
df_no_zipcode = df_bnb_train[df_bnb_train['zipcode'].isna()]
if not df_no_zipcode.empty:
    # Realizar la predicción y asignarla a las filas correspondientes
    predicted_zipcodes = knn.predict(df_no_zipcode[location_features])
    df_bnb_train.loc[df_bnb_train['zipcode'].isna(), 'zipcode'] = predicted_zipcodes

# Verificar si quedan nulos en la columna 'zipcode'
print("Nulos restantes en 'zipcode' después de la imputación:", df_bnb_train['zipcode'].isnull().sum())


Nulos restantes en 'zipcode' después de la imputación: 0


In [60]:
from sklearn.neighbors import KNeighborsClassifier

# Filtrar registros con 'neighbourhood_cleansed' conocidos para entrenar el modelo
df_with_neighbourhood_cleansed = df_bnb_train.dropna(subset=['neighbourhood_cleansed']).copy()

# Convertir 'neighbourhood_cleansed' a un tipo categórico para el modelo
df_with_neighbourhood_cleansed['neighbourhood_cleansed'] = df_with_neighbourhood_cleansed['neighbourhood_cleansed'].astype(str)

# Definir las características de ubicación para el modelo
location_features = ['latitude', 'longitude']

# Entrenar el modelo KNN con las filas conocidas
knn_neighbourhood_cleansed = KNeighborsClassifier(n_neighbors=5)
knn_neighbourhood_cleansed.fit(df_with_neighbourhood_cleansed[location_features], df_with_neighbourhood_cleansed['neighbourhood_cleansed'])

# Predecir 'neighbourhood_cleansed' para las filas con valores nulos en esa columna
df_no_neighbourhood_cleansed = df_bnb_train[df_bnb_train['neighbourhood_cleansed'].isna()]
predicted_neighbourhoods_cleansed = knn_neighbourhood_cleansed.predict(df_no_neighbourhood_cleansed[location_features])

# Asignar los valores predichos en el DataFrame original
df_bnb_train.loc[df_bnb_train['neighbourhood_cleansed'].isna(), 'neighbourhood_cleansed'] = predicted_neighbourhoods_cleansed

# Verificar si quedan nulos en 'neighbourhood_cleansed'
print("Nulos restantes en 'neighbourhood_cleansed' después de la imputación:", df_bnb_train['neighbourhood_cleansed'].isnull().sum())


Nulos restantes en 'neighbourhood_cleansed' después de la imputación: 0


In [61]:
from sklearn.neighbors import KNeighborsClassifier

# Paso 1: Imputar basándonos en combinaciones jerárquicas
def imputar_neighbourhood_group(row):
    if pd.isna(row['neighbourhood_group_cleansed']):
        # Coincidencia exacta con todos los campos
        subset = df_bnb_train[
            (df_bnb_train['zipcode'] == row['zipcode']) &
            (df_bnb_train['latitude'] == row['latitude']) &
            (df_bnb_train['longitude'] == row['longitude']) &
            (df_bnb_train['city'] == row['city'])
        ]
        
        # Relajar condiciones
        if subset.empty:
            subset = df_bnb_train[
                (df_bnb_train['zipcode'] == row['zipcode']) &
                (df_bnb_train['city'] == row['city'])
            ]
        
        if subset.empty:
            subset = df_bnb_train[df_bnb_train['zipcode'] == row['zipcode']]
        
        if not subset.empty and not subset['neighbourhood_group_cleansed'].mode().empty:
            return subset['neighbourhood_group_cleansed'].mode()[0]
    return row['neighbourhood_group_cleansed']

df_bnb_train['neighbourhood_group_cleansed'] = df_bnb_train.apply(imputar_neighbourhood_group, axis=1)

# Paso 2: Aplicar KNN para registros restantes
df_no_neighbourhood_group = df_bnb_train[df_bnb_train['neighbourhood_group_cleansed'].isna()]
df_with_neighbourhood_group = df_bnb_train.dropna(subset=['neighbourhood_group_cleansed']).copy()

# Convertir neighbourhood_group_cleansed a categórico
df_with_neighbourhood_group['neighbourhood_group_cleansed'] = df_with_neighbourhood_group['neighbourhood_group_cleansed'].astype(str)

knn = KNeighborsClassifier(n_neighbors=5)
location_features = ['latitude', 'longitude']

# Entrenar KNN solo con datos completos
knn.fit(df_with_neighbourhood_group[location_features], df_with_neighbourhood_group['neighbourhood_group_cleansed'])

# Predecir valores faltantes
if not df_no_neighbourhood_group.empty:
    df_bnb_train.loc[df_bnb_train['neighbourhood_group_cleansed'].isna(), 'neighbourhood_group_cleansed'] = knn.predict(df_no_neighbourhood_group[location_features])

# Verificar nulos restantes
print("Nulos restantes en 'neighbourhood_group_cleansed' después de la imputación:", df_bnb_train['neighbourhood_group_cleansed'].isnull().sum())


Nulos restantes en 'neighbourhood_group_cleansed' después de la imputación: 0


In [62]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder

# Paso 1: Convertir temporalmente a valores numéricos para KNN
temp_df = df_bnb_train.copy()
label_encoders = {}
for col in ['neighbourhood_cleansed', 'neighbourhood_group_cleansed']:
    le = LabelEncoder()
    temp_df[col] = le.fit_transform(temp_df[col].astype(str))
    label_encoders[col] = le

# Filtrar filas con valores en 'neighbourhood' para entrenar
df_with_neighbourhood = temp_df.dropna(subset=['neighbourhood']).copy()

# Entrenar KNN en características geográficas y categóricas temporales
location_features = ['latitude', 'longitude', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed']
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(df_with_neighbourhood[location_features], df_with_neighbourhood['neighbourhood'])

# Predecir 'neighbourhood' para registros sin valor
df_no_neighbourhood = temp_df[temp_df['neighbourhood'].isna()]
if not df_no_neighbourhood.empty:
    predicted_neighbourhoods = knn.predict(df_no_neighbourhood[location_features])
    df_bnb_train.loc[df_bnb_train['neighbourhood'].isna(), 'neighbourhood'] = predicted_neighbourhoods

# Verificar si quedan nulos en 'neighbourhood'
print("Nulos restantes en 'neighbourhood' después de la imputación:", df_bnb_train['neighbourhood'].isnull().sum())


Nulos restantes en 'neighbourhood' después de la imputación: 0


In [63]:
df_bnb_train.isnull().sum()

summary                         0
description                     0
host_total_listings_count       0
neighbourhood                   0
neighbourhood_cleansed          0
neighbourhood_group_cleansed    0
city                            0
state                           0
zipcode                         0
market                          0
smart_location                  0
country_code                    0
country                         0
latitude                        0
longitude                       0
property_type                   0
room_type                       0
accommodates                    0
bathrooms                       0
bedrooms                        0
beds                            0
bed_type                        0
amenities                       0
price                           0
weekly_price                    0
monthly_price                   0
security_deposit                0
cleaning_fee                    0
guests_included                 0
extra_people  

## por fin no tenemos mas NULOS!! ahora...

## CAMBIAR LAS CATEGORICAS A NUMERICAS FALTANTES

Emepecemos con amenities, summary y description.
amenities: tiene 128 cateogrias unicas, las dividire en basicas, estandard y high y poderles asignar un peso y score para que el modelo entienda su importancia para el precio
summary y description: Extraeré términos o frases recurrentes que puedan indicar características importantes de la propiedad, haré un filtrado de las palabras clave en ambas columnas (summary y description) para reducirlas y generaré una columna content_score que sume la cantidad de palabras clave importantes presentes en cada propiedad.

In [64]:
categorical_columns = df_bnb_train.select_dtypes(include=['object', 'category']).columns
print(categorical_columns)

Index(['summary', 'description', 'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'city', 'state', 'zipcode', 'market',
       'smart_location', 'country_code', 'country', 'property_type',
       'room_type', 'bed_type', 'amenities', 'cancellation_policy'],
      dtype='object')


In [65]:
# Ver los tipos únicos de amenities presentes en el dataset
unique_amenities = df_bnb_train['amenities'].str.split(',', expand=True).stack().str.strip().unique()

# Imprimir la cantidad de amenities únicas
print("Número de amenities únicas:", len(unique_amenities))

# Opcionalmente, puedes ver la lista de amenities únicas
unique_amenities


Número de amenities únicas: 128


array(['tv', 'internet', 'wireless internet', 'air conditioning',
       'kitchen', 'doorman', 'elevator in building',
       'buzzerwireless intercom', 'heating', 'familykid friendly',
       'washer', 'essentials', 'hangers', 'smoke detector',
       'carbon monoxide detector', 'shampoo', '24hour checkin',
       'hair dryer', 'iron', 'laptop friendly workspace',
       'wheelchair accessible', 'pool', 'free parking on premises',
       'breakfast', 'suitable for events', 'first aid kit', 'safety card',
       'fire extinguisher', 'lock on bedroom door', 'smoking allowed',
       'cable tv', 'translation missing enhostingamenity50',
       'translation missing enhostingamenity49', 'private entrance',
       'dryer', 'pets allowed', 'hot tub',
       'missing in friendly on aid enhostingamenity50 tv',
       'wireless enhostingamenity49', 'translation internet', 'air dryer',
       'laptop', 'indoor fireplace', 'gym', 'private living room',
       'pets live on this property', 'dogs',

In [66]:
# Definir las categorías de amenidades con sus pesos
high_amenities = [
    'pool', 'hot tub', 'gym', 'indoor fireplace', 'bbq grill', 'ev charger', 
    'doorman', 'private entrance', 'elevator in building', 'suitable for events', 
    'jacuzzi', 'smartlock', 'free parking on premises', 'fireplace guards', 'private living room',
    'game console', 'patio or balcony', 'garden or backyard', 'paid parking off premises', 
    'fire extinguisher'
]

standard_amenities = [
    'air conditioning', 'heating', 'washer', 'dryer', 'dishwasher', 'microwave', 'coffee maker',
    'refrigerator', 'cooking basics', 'oven', 'laptop friendly workspace', 'iron', 'hair dryer',
    'self check-in', 'doorman entry', 'crib', 'bathtub', 'breakfast', 'pets allowed', 
    'pets live on this property', 'cat(s)', 'dog(s)', 'other pet(s)', 'baby bath', 'high chair',
    'children’s books and toys', 'table corner guards', 'stair gates', 'children’s dinnerware', 
    'pack ’n play/travel crib', 'babysitter recommendations', 'changing table', 'wheelchair accessible', 
    'room-darkening shades', 'long term stays allowed', 'keypad', 'smoking allowed', 
    'window guards', 'luggage dropoff allowed', 'outlet covers', 'first aid kit', 
    'carbon monoxide detector', 'extra pillows and blankets', 'bed linens', 'hot water', 'air', 
    'air dryer', 'lockbox', 'smartlock', 'refrigerator', 'familykid friendly', 'kitchen', 
    'stove', 'washer / dryer', 'missing in friendly on aid enhostingamenity50 tv', 
    'translation enhostingamenity50 internet', 'missing in friendly aid on internet', 
    'missing in friendly enhostingamenity50 on enhostingamenity49', 'translation tv', 
    'wireless aid workspace', 'table corner guards', 'stair gates'
]

basic_amenities = [
    'wifi', 'cable tv', 'internet', 'smoke detector', 'safety card', '24-hour check-in',
    'buzzer/wireless intercom', 'wireless internet', 'lock on bedroom door', 
    'dishes and silverware', 'path to entrance lit at night', 'translation missing enhostingamenity49',
    'translation missing enhostingamenity50', 'tv', 'fire extinguisher', 'essentials', 
    'familykid friendly', 'hangers', 'shampoo', 'lock on bedroom door', 'iron', 'air', 
    'outlet covers', 'translation aid internet', 'translation friendly in wireless tv', 
    'missing on tv', 'wireless enhostingamenity50 dryer', 'laptop in workspace intercom', 
    'laptop building', 'buzzerwireless', 'air on friendly parking tv', 'wireless detector', 
    'laptop intercom', 'wireless friendly dryer', 'hair dryer', 'buzzerwireless missing tv', 
    'wifi', 'tv', 'wireless', 'smoke detector', 'path to entrance lit at night', 
    'dishes and silverware', 'wireless internet', 'lock on bedroom door', 'carbon monoxide detector'
]


# Asignar pesos a cada categoría de amenidades
high_weight = 3
standard_weight = 2
basic_weight = 1

# Definir la función para calcular el puntaje de amenidades
def calculate_amenity_score(amenities):
    if pd.isna(amenities):
        return 0  # Si no hay amenidades, el puntaje será 0
    
    # Dividir las amenidades en una lista de amenidades individuales
    amenities_list = amenities.lower().split(',')
    
    # Contadores para cada categoría
    high_count = sum(amenity.strip() in high_amenities for amenity in amenities_list)
    standard_count = sum(amenity.strip() in standard_amenities for amenity in amenities_list)
    basic_count = sum(amenity.strip() in basic_amenities for amenity in amenities_list)
    
    # Calcular el puntaje total
    return (high_count * high_weight) + (standard_count * standard_weight) + (basic_count * basic_weight)

# Aplicar la función para calcular el puntaje de amenidades en el dataset
df_bnb_train['amenity_score'] = df_bnb_train['amenities'].apply(calculate_amenity_score)

# Mostrar algunos resultados para verificar el puntaje
print(df_bnb_train[['amenity_score']].head(5))


   amenity_score
0             22
1             32
2             50
3              9
4             25


In [67]:
# Eliminar la columna original de 'amenities' si ya no es necesaria
df_bnb_train = df_bnb_train.drop(columns=['amenities'])

In [68]:
# Procesar summary y description por contenido de relevancia
# definir keywords
relevant_keywords = ['spacious', 'luxury', 'cozy', 'modern', 'renovated', 'central', 'wifi', 'parking', 'balcony', 'kitchen']

# funcion calculate_content_score
def calculate_content_score(text):
    if pd.isna(text):
        return 0
    words = text.lower().split()
    score = sum(1 for word in words if word in relevant_keywords)
    return score

# aplicar a `summary` y `description`
df_bnb_train['summary_content_score'] = df_bnb_train['summary'].apply(calculate_content_score)
df_bnb_train['description_content_score'] = df_bnb_train['description'].apply(calculate_content_score)


# Final check
print(df_bnb_train[['amenity_score', 'summary_content_score', 'description_content_score']].head())

   amenity_score  summary_content_score  description_content_score
0             22                      0                          1
1             32                      0                          1
2             50                      0                          0
3              9                      0                          0
4             25                      3                          3


In [69]:
# Drop original text columns after extraction
df_bnb_train = df_bnb_train.drop(columns=['summary', 'description'])

In [70]:
df_bnb_train.head()

host_total_listings_count neighbourhood neighbourhood_cleansed  \
0                        2.0      jernimos               jernimos   
1                        1.0           sol                    sol   
2                       16.0   carabanchel           vista alegre   
3                      114.0   embajadores            embajadores   
4                        2.0    gaztambide             gaztambide   

  neighbourhood_group_cleansed    city                state zipcode  market  \
0                       retiro  madrid  comunidad de madrid   28014  madrid   
1                       centro  madrid  comunidad de madrid   28012  madrid   
2                  carabanchel  madrid  comunidad de madrid   28025  madrid   
3                       centro  madrid  comunidad de madrid   28012  madrid   
4                      chamber  madrid                   28   28015  madrid   

  smart_location country_code country   latitude  longitude property_type  \
0  madrid, spain           es   spain  40.407732  -3.684819     apartment   
1  madrid, spain           es   spain  40.415802  -3.705340     apartment   
2  madrid, spain           es   spain  40.389048  -3.740374     apartment   
3  madrid, spain           es   spain  40.412814  -3.703052     apartment   
4  madrid, spain           es   spain  40.438631  -3.713716     apartment   

        room_type  accommodates  bathrooms  bedrooms  beds  bed_type  price  \
0  entire homeapt             4          1         1     2  real bed   60.0   
1  entire homeapt             4          1         1     2  real bed   50.0   
2     shared room             1          2         1     8  real bed   10.0   
3    private room             2          3         1     1  real bed   30.0   
4    private room             2          1         1     1  real bed   32.0   

   weekly_price  monthly_price  security_deposit  cleaning_fee  \
0         550.0         1250.0             150.0          25.0   
1         350.0         1500.0             150.0          15.0   
2          70.0          300.0             150.0           5.0   
3         210.0          900.0             150.0          20.0   
4         224.0          960.0             150.0          20.0   

   guests_included  extra_people  minimum_nights  maximum_nights  \
0                1             0               2            1125   
1                1             0               1            1125   
2                1             0               3              30   
3                1             0              10            1125   
4                1            10               1            1125   

   availability_30  availability_60  availability_90  availability_365  \
0                9               32               52               117   
1               15               39               64               208   
2               14               44               74               140   
3                0                6               36               311   
4                7               34               62               337   

   number_of_reviews  review_scores_rating  review_scores_accuracy  \
0                 12                  95.0                     9.0   
1                 20                  91.0                     9.0   
2                  0                  94.0                    10.0   
3                  0                  94.0                    10.0   
4                 97                  92.0                     9.0   

   review_scores_cleanliness  review_scores_checkin  \
0                       10.0                   10.0   
1                        9.0                   10.0   
2                       10.0                   10.0   
3                       10.0                   10.0   
4                        9.0                    9.0   

   review_scores_communication  review_scores_location  review_scores_value  \
0                         10.0                    10.0                  9.0   
1             

In [71]:
categorical_columns = df_bnb_train.select_dtypes(include=['object', 'category']).columns
print(categorical_columns)


Index(['neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'city', 'state', 'zipcode', 'market',
       'smart_location', 'country_code', 'country', 'property_type',
       'room_type', 'bed_type', 'cancellation_policy'],
      dtype='object')


## *Seguimos con property_type* ##

Agrupare el número de columnas en función de sus rangos de precios para optimizar el modelo al utilizar una codificación ordinal mediante property_type_weighted, sin añadir múltiples columnas, asegurando una interpretación directa y eficiente para el modelo.

In [72]:
# Mostrar las categorías únicas de 'property_type'
unique_property_type_cleaned = df_bnb_train['property_type'].unique()
print("Categorías únicas de property_type:", unique_property_type_cleaned)

# Mostrar el número total de categorías únicas
total_unique_property_types = len(unique_property_type_cleaned)
print("\nNúmero total de categorías únicas en 'property_type':", total_unique_property_types)



Categorías únicas de property_type: ['apartment' 'loft' 'house' 'bed  breakfast' 'dorm' 'chalet' 'condominium'
 'guesthouse' 'hostel' 'other' 'villa' 'boutique hotel' 'camperrv'
 'casa particular' 'townhouse' 'serviced apartment' 'guest suite' 'boat'
 'tent' 'earth house' 'bungalow']

Número total de categorías únicas en 'property_type': 21


In [73]:
# Calcular el precio promedio para cada tipo de propiedad original
average_price_by_property_type = df_bnb_train.groupby('property_type')['price'].mean().sort_values()

# Mostrar el precio promedio por tipo de propiedad original
print("Precio promedio por tipo de propiedad:")
print(average_price_by_property_type)


Precio promedio por tipo de propiedad:
property_type
earth house            20.500000
guest suite            20.500000
tent                   25.000000
casa particular        31.666667
camperrv               35.666667
bed  breakfast         39.558394
guesthouse             43.781250
hostel                 47.923077
dorm                   48.513514
bungalow               56.000000
serviced apartment     64.888889
condominium            65.954225
other                  66.754386
boutique hotel         68.000000
apartment              72.276412
loft                   80.983871
chalet                 84.227273
house                  95.482028
boat                  102.000000
townhouse             108.666667
villa                 264.533333
Name: price, dtype: float64


In [74]:
# Agrupación basada en el precio promedio observado
df_bnb_train['property_type_grouped'] = df_bnb_train['property_type'].replace({
    'villa': 'high_price_accommodation',
    'house': 'mid_price_accommodation',
    'townhouse': 'mid_price_accommodation',
    'boat': 'mid_price_accommodation',
    'chalet': 'mid_price_accommodation',
    'loft': 'mid_price_accommodation',
    'apartment': 'affordable_accommodation',
    'condominium': 'affordable_accommodation',
    'serviced apartment': 'affordable_accommodation',
    'bungalow': 'affordable_accommodation',
    'boutique hotel': 'affordable_accommodation',
    'guesthouse': 'low_price_accommodation',
    'dorm': 'low_price_accommodation',
    'hostel': 'low_price_accommodation',
    'bed  breakfast': 'low_price_accommodation',
    'casa particular': 'low_price_accommodation',
    'camperrv': 'low_price_accommodation',
    'tent': 'low_price_accommodation',
    'earth house': 'low_price_accommodation',
    'guest suite': 'low_price_accommodation',
    'other': 'unique_accommodation',
    'timeshare':'low_price_accommodation'
})

print("Valores nulos en property_type_grouped:", df_bnb_train['property_type_grouped'].isna().sum())

Valores nulos en property_type_grouped: 0


In [75]:

# Asignar pesos a las agrupaciones
property_type_group_weights = {
    'high_price_accommodation': 4,
    'mid_price_accommodation': 3,
    'affordable_accommodation': 2,
    'low_price_accommodation': 1,
    'unique_accommodation': 2
}

# Mapear los pesos a la nueva columna
df_bnb_train['property_type_weighted'] = df_bnb_train['property_type_grouped'].map(property_type_group_weights)


print("Valores nulos en property_type_weighted:", df_bnb_train['property_type_weighted'].isna().sum())

Valores nulos en property_type_weighted: 0


In [76]:
# Eliminar columnas redundantes
df_bnb_train = df_bnb_train.drop(columns=['property_type', 'property_type_grouped'])

In [77]:
df_bnb_train.isnull().sum()

host_total_listings_count       0
neighbourhood                   0
neighbourhood_cleansed          0
neighbourhood_group_cleansed    0
city                            0
state                           0
zipcode                         0
market                          0
smart_location                  0
country_code                    0
country                         0
latitude                        0
longitude                       0
room_type                       0
accommodates                    0
bathrooms                       0
bedrooms                        0
beds                            0
bed_type                        0
price                           0
weekly_price                    0
monthly_price                   0
security_deposit                0
cleaning_fee                    0
guests_included                 0
extra_people                    0
minimum_nights                  0
maximum_nights                  0
availability_30                 0
availability_6

### *Seguimos con room_type y bed_type* ###

Target Encoding: Con esta codificación, el modelo asigna automáticamente más peso a las categorías con un mayor precio promedio, ayudando a la predicción de price.

Mejora en interpretabilidad y evita alta dimensionalidad. Las categorías con mayor valor tendrán un impacto mayor en la predicción del precio, lo cual es crucial para entender la contribución de cada variable al precio.

In [78]:
# Obtener el promedio de 'price' para cada categoría en 'room_type' y 'bed_type'
room_type_mean = df_bnb_train.groupby('room_type')['price'].mean()
bed_type_mean = df_bnb_train.groupby('bed_type')['price'].mean()

# Mapear esos valores al dataset como codificación
df_bnb_train['room_type_encoded'] = df_bnb_train['room_type'].map(room_type_mean)
df_bnb_train['bed_type_encoded'] = df_bnb_train['bed_type'].map(bed_type_mean)

# Verificar el resultado final
print(df_bnb_train[['room_type_encoded', 'bed_type_encoded']].head())


   room_type_encoded  bed_type_encoded
0          95.029064         74.055858
1          95.029064         74.055858
2          31.320988         74.055858
3          40.901141         74.055858
4          40.901141         74.055858


In [79]:
# Eliminar las columnas originales después de la codificación
df_bnb_train = df_bnb_train.drop(columns=['room_type', 'bed_type'])

In [80]:
df_bnb_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11824 entries, 0 to 11823
Data columns (total 50 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   host_total_listings_count     11824 non-null  float64
 1   neighbourhood                 11824 non-null  object 
 2   neighbourhood_cleansed        11824 non-null  object 
 3   neighbourhood_group_cleansed  11824 non-null  object 
 4   city                          11824 non-null  object 
 5   state                         11824 non-null  object 
 6   zipcode                       11824 non-null  object 
 7   market                        11824 non-null  object 
 8   smart_location                11824 non-null  object 
 9   country_code                  11824 non-null  object 
 10  country                       11824 non-null  object 
 11  latitude                      11824 non-null  float64
 12  longitude                     11824 non-null  float64
 13  a

In [81]:
categorical_columns = df_bnb_train.select_dtypes(include=['object', 'category']).columns
print(categorical_columns)


Index(['neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'city', 'state', 'zipcode', 'market',
       'smart_location', 'country_code', 'country', 'cancellation_policy'],
      dtype='object')


In [82]:
# Cancellation Policy a numerica

cancellation_p_map = {
    'flexible': 1,
    'flexiblenew': 1,
    'moderate': 2,
    'moderatenew': 2,
    'strict': 3,
    'strictnew': 3,
    'superstrict30': 4,
    'superstrict60': 5    
}

df_bnb_train['cancellation_policy_numeric'] =  df_bnb_train['cancellation_policy'].map(cancellation_p_map)

In [83]:
# Eliminar la columna original 'cancellation_policy' para evitar redundancia
df_bnb_train = df_bnb_train.drop(columns=['cancellation_policy'])

In [84]:
categorical_columns = df_bnb_train.select_dtypes(include=['object', 'category']).columns
print(categorical_columns)

Index(['neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'city', 'state', 'zipcode', 'market',
       'smart_location', 'country_code', 'country'],
      dtype='object')


In [85]:
unique_neighbourhood = pd.concat([
    df_bnb_train['neighbourhood'], 
    df_bnb_train['neighbourhood_cleansed'],
    df_bnb_train['neighbourhood_group_cleansed']
]).str.split(',', expand=True).stack().str.strip().unique()

unique_neighbourhood


# Mostrar los valores únicos y el total
print("Valores únicos de neighbourhoods:", unique_neighbourhood)


Valores únicos de neighbourhoods: ['jernimos' 'sol' 'carabanchel' 'embajadores' 'gaztambide' 'palacio'
 'san blas' 'goya' 'fuente del berro' 'ibiza' 'la latina' 'argelles'
 'usera' 'malasaa' 'etterbeek' 'lista' 'vallehermosa' 'prosperidad'
 'ciudad lineal' 'pacifico' 'cortes' 'palos do moguer' 'justicia'
 'cuatro caminos' 'arapiles' 'castillejos' 'castellana' 'passy' 'almagro'
 'guindalera' 'barajas' 'acacias' 'hispanoamrica' 'viclvaro'
 'puente de vallecas' 'aluche' 'moratalaz' 'almenara' 'fuencarralel pardo'
 'esquilino' 'trafalgar' 'rios rosas' 'bondi' 'greenwood' 'midwilshire'
 'berruguete' 'hortaleza' 'castilla' 'lb of sutton' 'madeleine  vendme'
 'el raval' 'indische buurt' 'docklands' 'prenzlauer berg' 'imperial'
 'el born' 'mitte' 'recoletos' 'moncloa' 'pasadena' 'balham' 'la chopera'
 'acton' 'santsmontjuc' 'batignolles' 'delicias' 'dreta de leixample'
 'kdbyen' 'villaverde' 'fairlawn' 'darlinghurst' 'eckington' 'el viso'
 'islington' 'riverbend' 'la chapelle' 'chelsea' 'holly

In [86]:
unique_neighbourhood_group_cleansed = df_bnb_train['neighbourhood_group_cleansed'].str.split(',', expand=True).stack().str.strip().unique()
unique_neighbourhood_group_cleansed

# Mostrar los valores únicos y el total
print("Valores únicos de neighbourhood:", unique_neighbourhood_group_cleansed)


Valores únicos de neighbourhood: ['retiro' 'centro' 'carabanchel' 'chamber' 'santsmontjuc' 'salamanca'
 'moncloa  aravaca' 'usera' 'friedrichshainkreuzberg' 'chamartn'
 'ciudad lineal' 'arganzuela' 'tetun' 'ciutat vella' 'hortaguinard'
 'barajas' 'viclvaro' 'puente de vallecas' 'latina' 'moratalaz'
 'fuencarral  el pardo' 'isole' 'other neighborhoods' 'capitol hill'
 'hortaleza' 'mitte' 'pankow' 'eixample' 'villaverde'
 'san blas  canillejas' 'brooklyn' 'manhattan' 'sant mart' 'magnolia'
 'sarrisant gervasi' 'grcia' 'villa de vallecas' 'les corts' 'neuklln'
 'queens' 'beacon hill' 'tempelhof  schneberg' 'treptow  kpenick' 'bronx'
 'nou barris' 'charlottenburgwilm' 'ballard']


In [87]:
unique_neighbourhood_cleansed = df_bnb_train['neighbourhood_cleansed'].str.split(',', expand=True).stack().str.strip().unique()
unique_neighbourhood_cleansed

# Mostrar los valores únicos y el total
print("Valores únicos de neighbourhood:", unique_neighbourhood_cleansed)

Valores únicos de neighbourhood: ['jernimos' 'sol' 'vista alegre' 'embajadores' 'gaztambide' 'palacio'
 'calvi' 'goya' 'fuente del berro' 'ibiza' 'casa de campo' 'almendrales'
 'moscard' 'universidad' 'etterbeek' 'lista' 'vallehermoso' 'prosperidad'
 'costillares' 'palma de mallorca' 'ventas' 'cortes' 'palos de moguer'
 'argelles' 'justicia' 'cuatro caminos' 'art' 'castillejos' 'castellana'
 'passy' 'almagro' 'guindalera' 'san isidro' 'timn' 'acacias' 'aeropuerto'
 'hispanoamrica' 'ambroz' 'san diego' 'crmenes' 'vinateros' 'arapiles'
 'almenara' 'pueblo nuevo' 'peagrande' 'concepcin' 'i centro storico'
 'pacfico' 'san juan bautista' 'palomeras sureste' 'mirasierra'
 'trafalgar' 'quintana' 'comillas' 'rios rosas' 'puerta bonita' 'lucero'
 'waverley' 'phinney ridge' 'midwilshire' 'berruguete' 'canillas'
 'castilla' 'puerta del angel' 'sutton' 'luxembourg' 'el raval'
 'pinar del rey' 'oudoost' 'dublin city' 'prenzlauer berg sd' 'imperial'
 'santa margalida' 'brunnenstr sd' 'recoletos' 'ar

#### Ya no tenemos nulos pero si varias variables categoricas!! 
*Continuamos con Codificacion de variables categoricas, por ejemplo 'neighbourhood', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed' con target Encoding:*

*neighbourhood_group_cleansed: tiene 47 valores únicos y puede representar niveles de zona, label encoding o ordinal encoding sería más adecuado. Esto mantiene un orden y evita crear múltiples columnas que podrían añadir complejidad sin aportar mucho detalle.

*neighbourhood_cleansed: 442 valores únicos, target encoding podría ser lo mejor, ya que reduce las dimensiones y permite al modelo captar la relación directa entre el vecindario y la variable objetivo (precio), sin agregar muchas variables dummy.

*neighbourhood: Tiene 350 valores únicos y no parece aportar una jerarquía. Si la variable es relevante, target encoding también es una opción aquí.

In [88]:
# Codificar `neighbourhood_group_cleansed` con Label Encoding

from sklearn.preprocessing import LabelEncoder


label_encoder_group = LabelEncoder()
df_bnb_train['neighbourhood_group_cleansed_encoded'] = label_encoder_group.fit_transform(df_bnb_train['neighbourhood_group_cleansed'])




In [89]:
# Definir el mapeo para `neighbourhood_cleansed` Target Encoding
mean_map = {}
mean_map['neighbourhood_cleansed'] = df_bnb_train.groupby('neighbourhood_cleansed')['price'].mean()

# Aplicar target encoding en `neighbourhood_cleansed`
df_bnb_train['neighbourhood_cleansed_encoded'] = df_bnb_train['neighbourhood_cleansed'].map(mean_map['neighbourhood_cleansed'])


In [90]:
# Definir el mapeo para `neighbourhood` Target Encoding
mean_map['neighbourhood'] = df_bnb_train.groupby('neighbourhood')['price'].mean()

# Aplicar target encoding en `neighbourhood`
df_bnb_train['neighbourhood_encoded'] = df_bnb_train['neighbourhood'].map(mean_map['neighbourhood'])


In [91]:
# Verificar si hay nulos en las nuevas columnas codificadas
print("Verificación de nulos después de la codificación:")
print(df_bnb_train[['neighbourhood_cleansed_encoded', 'neighbourhood_encoded', 'neighbourhood_group_cleansed_encoded']].isnull().sum())

# Mostrar las primeras filas para comprobar
df_bnb_train[['neighbourhood_cleansed', 'neighbourhood_cleansed_encoded', 'neighbourhood', 'neighbourhood_encoded', 'neighbourhood_group_cleansed', 'neighbourhood_group_cleansed_encoded']].head()


Verificación de nulos después de la codificación:
neighbourhood_cleansed_encoded          0
neighbourhood_encoded                   0
neighbourhood_group_cleansed_encoded    0
dtype: int64


neighbourhood_cleansed  neighbourhood_cleansed_encoded neighbourhood  \
0               jernimos                      104.600000      jernimos   
1                    sol                       85.710220           sol   
2           vista alegre                       37.074074   carabanchel   
3            embajadores                       60.703779   embajadores   
4             gaztambide                       56.000000    gaztambide   

   neighbourhood_encoded neighbourhood_group_cleansed  \
0             104.121212                       retiro   
1              84.620205                       centro   
2              39.979522                  carabanchel   
3              59.554729                       centro   
4              61.982301                      chamber   

   neighbourhood_group_cleansed_encoded  
0                                    34  
1                                     8  
2                                     7  
3                                     8  
4                                    10

In [92]:
# Eliminar las columnas categóricas originales después del encoding
df_bnb_train.drop(columns=['neighbourhood', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed'], inplace=True)


In [93]:
categorical_columns = df_bnb_train.select_dtypes(include=['object', 'category']).columns
print(categorical_columns)

Index(['city', 'state', 'zipcode', 'market', 'smart_location', 'country_code',
       'country'],
      dtype='object')


*Target encoding para: city, state, zipcode, market, country_code o country*

*Eliminar smart_location si es redundante.*

**city:** Posiblemente tenga un alto número de categorías únicas, lo cual impacta en la granularidad geográfica. Si el número de categorías es alto, sería más conveniente usar target encoding para reflejar cómo el precio medio varía entre ciudades. Esto agrega valor al modelo sin generar demasiadas columnas.

**state:** Dependiendo de la diversidad de valores, podría usarse target encoding para capturar las variaciones en precio entre estados, especialmente si el número de valores es moderado.

**zipcode:** Si los zipcodes son numerosos y específicos, puede aportar más al precio si se usa target encoding, dado que los precios pueden variar considerablemente por zonas de código postal. Esto también previene la creación de una cantidad excesiva de columnas.

**market:** Esta categoría representa una segmentación más amplia del lugar, probablemente a nivel de mercado regional. Si los valores son numerosos, target encoding es ideal para reflejar el precio medio por mercado.

**smart_location:** Si smart_location sigue una estructura que incluye ciudad y algún otro descriptor único, se recomienda eliminarla tras verificar que es redundante con city y zipcode. Mantenerla podría duplicar información.

**country_code y country:**  cada país o código de país se transforma en una representación numérica basada en la relación con price.

In [94]:
# Mostrar los primeros valores únicos de 'smart_location' para entender su contenido y si duplica info que hay en city
print(df_bnb_train['smart_location'].unique()[:10])  # Solo los primeros 10 valores para tener una idea


['madrid, spain' 'illetes, spain' 'etterbeek, belgium' 'palma, spain'
 'betlem, spain' 'paris, france' ', spain' 'rome, italy'
 'bondi, australia' 'seattle, wa']


In [95]:
# Código para eliminar la columna 'smart_location' del DataFrame de entrenamiento
df_bnb_train = df_bnb_train.drop(columns=['smart_location'])



In [96]:
# Verificar si 'smart_location' está presente en el DataFrame
if 'smart_location' in df_bnb_train.columns:
    print("'smart_location' sigue en el DataFrame.")
else:
    print("'smart_location' fue descartada del DataFrame.")


'smart_location' fue descartada del DataFrame.


In [97]:
# Aplicar Target Encoding a 'city', 'state', 'zipcode', y 'market'
# Crear un diccionario para guardar los mapeos de cada columna, útil si se aplica en test
mean_map = {}
target_column = 'price'  # Columna objetivo para predecir

for column in ['city', 'state', 'zipcode', 'market']:
    mean = df_bnb_train.groupby(column)[target_column].mean()
    df_bnb_train[column] = df_bnb_train[column].map(mean)
    mean_map[column] = mean

In [98]:
# Contar países únicos en 'country'
unique_countries = df_bnb_train['country'].nunique()
print(f"Número de países únicos en 'country': {unique_countries}")

# Contar códigos de país únicos en 'country_code'
unique_country_codes = df_bnb_train['country_code'].nunique()
print(f"Número de códigos de país únicos en 'country_code': {unique_country_codes}")


Número de países únicos en 'country': 18
Número de códigos de país únicos en 'country_code': 17


In [99]:
# Aplicar Target Encoding a 'country'
mean_map = {}
mean = df_bnb_train.groupby('country')['price'].mean()
df_bnb_train['country'] = df_bnb_train['country'].map(mean)
mean_map['country'] = mean

# Eliminar la columna 'country_code' para evitar duplicación dei info
df_bnb_train.drop(columns=['country_code'], inplace=True)

# Confirmación de que la columna fue eliminada
print("Columnas después de aplicar target encoding y eliminar 'country_code':")
print(df_bnb_train.columns)



Columnas después de aplicar target encoding y eliminar 'country_code':
Index(['host_total_listings_count', 'city', 'state', 'zipcode', 'market',
       'country', 'latitude', 'longitude', 'accommodates', 'bathrooms',
       'bedrooms', 'beds', 'price', 'weekly_price', 'monthly_price',
       'security_deposit', 'cleaning_fee', 'guests_included', 'extra_people',
       'minimum_nights', 'maximum_nights', 'availability_30',
       'availability_60', 'availability_90', 'availability_365',
       'number_of_reviews', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'reviews_per_month', 'square_meters',
       'days_since_first_review', 'days_since_last_review',
       'review_activity_duration', 'amenity_score', 'summary_content_score',
       'description_content_score', 'property_type_weighted',
       'room_type_encoded', 'bed_type_e

In [100]:
categorical_columns = df_bnb_train.select_dtypes(include=['object', 'category']).columns
print(categorical_columns)

Index([], dtype='object')


In [101]:
df_bnb_train.head(30)


host_total_listings_count       city       state     zipcode      market  \
0                         2.0  67.821066   68.190554   83.679208   67.764071   
1                         1.0  67.821066   68.190554   67.575466   67.764071   
2                        16.0  67.821066   68.190554   38.073684   67.764071   
3                       114.0  67.821066   68.190554   67.575466   67.764071   
4                         2.0  67.821066   85.500000   61.730689   67.764071   
5                         1.0  67.821066   68.190554   67.575466   67.764071   
6                         1.0  67.821066   68.190554   67.767513   67.764071   
7                       114.0  67.821066   68.190554   81.976601   67.764071   
8                        68.0  54.500000  151.022059  150.900000  177.363333   
9                        28.0  67.821066   68.190554   84.478261   67.764071   
10                        4.0  67.821066   68.190554   67.575466   67.764071   
11                        8.0  67.821066   68.190554   52.051887   67.764071   
12                        2.0  67.821066   68.190554   78.441341   67.764071   
13                        2.0  67.821066   68.190554   67.575466   67.764071   
14                        4.0  67.821066   63.694394   63.775362   67.764071   
15                        1.0  67.821066   68.190554   67.575466   67.764071   
16                        2.0  67.821066   68.190554   78.441341   67.764071   
17                        1.0  67.821066   68.190554   67.575466   67.764071   
18                        5.0  67.821066   68.190554   67.767513   67.764071   
19                        6.0  67.821066   66.707415   67.575466   67.764071   
20                        4.0  67.821066   68.190554   38.583333   67.764071   
21                        2.0  67.821066   66.707415   38.583333   67.764071   
22                       10.0  67.821066   66.707415   74.421973   67.764071   
23                        4.0  25.000000   43.555556  103.750000   44.461538   
24                        1.0  67.821066   68.190554   84.478261   67.764071   
25                       40.0  67.821066   68.190554   73.405229   67.764071   
26                        1.0  67.821066   68.190554   67.575466   67.764071   
27                        1.0  67.821066   68.190554   64.149254   67.764071   
28                        6.0  67.821066   68.190554   47.238806   67.764071   
29                       10.0  67.821066   68.190554   81.976601   67.764071   

      country   latitude  longitude  accommodates  bathrooms  bedrooms  beds  \
0   71.774882  40.407732  -3.684819             4          1         1     2   
1   71.774882  40.415802  -3.705340             4          1         1     2   
2   71.774882  40.389048  -3.740374             1          2         1     8   
3   71.774882  40.412814  -3.703052             2          3         1     1   
4   71.774882  40.438631  -3.713716             2          1         1     1   
5   71.774882  40.411880  -3.702481             1          1         1     1   
6   71.774882  40.415087  -3.710994             4          1         1     2   
7   71.774882  40.418266  -3.705617             2          3         1     1   
8   71.774882  39.539871   2.592716             4          1         1     2   
9   71.774882  40.426410  -3.673278             4          2         2     3   
10  71.774882  40.408683  -3.700160             2          1         1     1   
11  71.774882  40.426880  -3.667827             2          2         1     2   
12  71.774882  40.417231  -3.678202             2          1         1     1   
13  71.774882  40.410093  -3.706216             4          1         1     1   
14  71.774882  40.429345  -3.722286             2          2         1     1   
15  71.774882  40.408427  -3.698600             4          1         1     2   
16  71.774882  40.420055  -3.676365             3          1         1     3   
17  71.774882  40.410659  -3.700538             4          1         0     3   
18 

In [ ]:
#revisaar days_since_first_review	days_since_last_review	review_activity_duration #

# revisaar days_since_first_review	days_since_last_review	review_activity_duration #

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Seleccionar solo las columnas numéricas para calcular la correlación
numeric_df_bnb = df_bnb.select_dtypes(include=[np.number])

# Calcular la matriz de correlación para todas las variables numéricas
correlation_matrix = numeric_df_bnb.corr()

# Visualizar el heatmap de las correlaciones
plt.figure(figsize=(25, 20))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5, fmt=".2f")
plt.title('Mapa de Calor de las Correlaciones entre Variables')
plt.tight_layout()
plt.show()

# Correlación específica con `price`
correlations_with_price = correlation_matrix['price'].sort_values(ascending=False)
print("Correlaciones de las variables con 'price':")
print(correlations_with_price)


### *Chequeamos distribucion y posibles Outliers gráficamente*
La gráfica muestra un sesgo completamente a la derecha, donde hay precios muy altos y la mayoria de precios se encuentran concentrados cerca a 0.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

#SIN PRICE LOG
# Asegurar que la columna 'price' sea numérica
bnb_data['Price'] = pd.to_numeric(bnb_data['Price'], errors='coerce')

# Crear un histograma para los valores ORIGINALES de 'price'
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.hist(bnb_data['Price'].dropna(), bins=50, color='blue', alpha=0.7)
plt.title('Distribución Original de Price')
plt.xlabel('Price')
plt.ylabel('Frecuencia')

#CON PRICE LOG
# Aplico la transformación logarítmica a la columna 'price' para reducir el impacto de outliers que se ven en el plot y mejorar la distribución de datos. Price tiene muchos valores extremos y esto ayudara a reducir su impacto.
bnb_data_cleaned = pd.read_csv("./data/airbnb-listings-cleaned.csv", sep=';', decimal='.', encoding='utf-8')
bnb_data_cleaned['Price'] = np.log1p(bnb_data_cleaned['Price'])

# Creo un histograma para los valores transformados de 'price'
plt.subplot(1, 2, 2)
plt.hist(bnb_data_cleaned['Price'].dropna(), bins=50, color='green', alpha=0.7)
plt.title('Distribución Logarítmica de Price despues de limpieza')
plt.xlabel('Log(price + 1)')
plt.ylabel('Frecuencia')

plt.tight_layout()
plt.show()

Eliminación de variables:
Alta Correlación:

Las variables con alta correlación entre sí pueden generar multicolinealidad, lo que podría complicar el modelo, especialmente para modelos lineales. Podemos eliminar algunas de estas variables. Según el heatmap:

neighbourhood, neighbourhood_cleansed, y neighbourhood_group_cleansed están altamente correlacionadas entre sí. Podríamos eliminar dos de ellas y quedarnos con solo una para reducir redundancia.
latitude y longitude tienen una correlación alta, pero es importante mantenerlos juntos ya que aportan información sobre la ubicación.

weekly_price y monthly_price están muy correlacionados con price (lo cual es esperado).

Las variables con baja correlación con el price (< 0.05) se pueden eliminar ya que tienen una baja capacidad predictiva para el target. 

Baja correlacion según el heatmap:
Variables como review_scores_accuracy, review_scores_checkin, review_scores_location, etc., tienen muy baja correlación con price.
country y country_code también tienen una correlación muy baja, por lo que podrían eliminarse.

In [ ]:
# Eliminar variables altamente correlacionadas y con baja correlación con 'price'
variables_a_eliminar = [
    'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'weekly_price', 'monthly_price', 
    'review_scores_accuracy', 'review_scores_checkin', 'review_scores_location', 
    'country', 'country_code'
]

df_bnb_reduced = df_bnb.drop(columns=variables_a_eliminar)

# Revisar las columnas restantes
print("Variables restantes después de la eliminación:")
print(df_bnb_reduced.columns)


In [104]:
# Generar nuevas variables
df_bnb_reduced['room_ratio'] = df_bnb_reduced['bedrooms'] / df_bnb_reduced['accommodates']
df_bnb_reduced['amenities_score'] = df_bnb_reduced['high_value_amenities'] * 3 + df_bnb_reduced['standard_value_amenities'] * 2 + df_bnb_reduced['basic_amenities']

# Reemplazar valores infinitos en la columna 'room_ratio'
df_bnb_reduced['room_ratio'] = df_bnb_reduced['room_ratio'].replace([np.inf, -np.inf], np.nan)

# Imputar los valores nulos restantes con 0
df_bnb_reduced['room_ratio'] = df_bnb_reduced['room_ratio'].fillna(0)


In [ ]:
# Verificar si las columnas categóricas existen antes de aplicar One-Hot Encoding
categorical_features = [col for col in ['property_type', 'cancellation_policy'] if col in df_bnb.columns]

# Realizar One-Hot Encoding solo si hay columnas categóricas disponibles
if categorical_features:
    df_bnb_encoded = pd.get_dummies(df_bnb, columns=categorical_features, drop_first=True)

# Revisar las columnas después del One-Hot Encoding
print("Columnas después del One-Hot Encoding:")
if 'df_bnb_encoded' in locals():
    print(df_bnb_encoded.columns)
else:
    print("No se aplicó One-Hot Encoding porque no se encontraron las columnas categóricas especificadas.")



In [ ]:
# Verificar si hay columnas no numéricas
non_numeric_cols = df_bnb_encoded.select_dtypes(include=['object']).columns
print(f"Columnas no numéricas en test: {non_numeric_cols}")


In [ ]:
# Verificar si hay valores nulos en el conjunto de test
missing_values = df_bnb_encoded.isnull().sum()
print(missing_values[missing_values > 0])


In [107]:
# Después de haber limpiado e imputado los datos en df_bnb

# 1. Convertir las variables categóricas en numéricas (en train)
df_bnb_encoded = pd.get_dummies(df_bnb, drop_first=True)

# 2. Separar las características (X_train) y el target (y_train)
X_train = df_bnb_encoded.drop(columns=['price']).values  # Eliminar 'price' de las características
y_train = df_bnb_encoded['price'].values  # Usar 'price' como target

# 3. Ajustar y escalar los datos de train
scaler = StandardScaler().fit(X_train)  # Ajustar el escalador solo en train
X_train_scaled = scaler.transform(X_train)  # Aplicar la transformación a los datos de train

# Ahora X_train_scaled contiene los datos de train listos para el modelo


In [ ]:
from sklearn.model_selection import cross_val_score, KFold
from sklearn.ensemble import RandomForestRegressor

# Definir las características y el target
X = df_bnb_encoded.drop(columns=['price'])
y = df_bnb_encoded['price']

# Definir el modelo
model = RandomForestRegressor(n_estimators=100, random_state=0)

# Definir la validación cruzada con 5 folds
cv = KFold(n_splits=5, shuffle=True, random_state=1)

# Realizar la validación cruzada
scores = cross_val_score(model, X, y, cv=cv, scoring='r2')

print("R^2 scores en cada fold:", scores)
print("R^2 promedio:", scores.mean())


In [ ]:
# Guardar las columnas de train después del preprocesamiento
df_train_encoded = pd.get_dummies(df_bnb, columns=categorical_features, drop_first=True)

# Guardar las columnas del conjunto de entrenamiento
train_columns = df_train_encoded.columns
joblib.dump(train_columns, 'train_columns.joblib')


### TEST

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
import joblib

# Cargar los datos de test
df_test = pd.read_csv('./data/airbnb-listings-cleaned_test.csv', sep=';', decimal='.', encoding='utf-8')

# Verificar si 'property_type' está en el DataFrame antes de intentar utilizarla
if 'property_type' in df_test.columns:
    # Imputar valores faltantes en 'square_meters' basados en 'property_type' y 'bedrooms'
    df_test['square_meters'] = df_test.groupby(['property_type', 'bedrooms'])['square_meters'].transform(lambda x: x.fillna(x.median()))

    # Imputar 'security_deposit' y 'cleaning_fee' basados en 'property_type'
    df_test['security_deposit'] = df_test.groupby('property_type')['security_deposit'].transform(lambda x: x.fillna(x.median()))
    df_test['cleaning_fee'] = df_test.groupby('property_type')['cleaning_fee'].transform(lambda x: x.fillna(x.median()))

# Continuar con las demás imputaciones, independientemente de si 'property_type' está presente
cols_to_impute_with_median = ['square_meters', 'security_deposit', 'cleaning_fee']
for col in cols_to_impute_with_median:
    df_test[col] = df_test[col].fillna(df_test[col].median())


cols_to_impute_with_median = ['square_meters', 'security_deposit', 'cleaning_fee']
for col in cols_to_impute_with_median:
    df_test[col] = df_test[col].fillna(df_test[col].median())

# Paso 2: Imputar valores de reseñas con las mismas reglas que en train
review_cols = [
    'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness',
    'review_scores_checkin', 'review_scores_communication', 'review_scores_location',
    'review_scores_value', 'reviews_per_month'
]

for col in review_cols:
    df_test[col] = df_test.apply(lambda x: 0 if x['number_of_reviews'] == 0 and pd.isnull(x[col]) else x[col], axis=1)
    df_test[col] = df_test[col].fillna(df_test[col].median())

# Paso 3: Imputar valores en las columnas geográficas (neighbourhood, city, etc.)

# Paso 1: Cargar el imputador ya ajustado en train
knn_imputer = joblib.load('knn_imputer.joblib')

# Paso 2: Imputar las columnas geográficas (neighbourhood, city, state, zipcode) en test
geo_cols = ['neighbourhood', 'city', 'state', 'zipcode']
coordinate_cols = ['latitude', 'longitude']

# Crear una copia de las columnas relevantes en test
location_data_test = df_test[geo_cols + coordinate_cols].copy()

# Convertir columnas categóricas en numéricas usando códigos
for col in geo_cols:
    location_data_test[col] = location_data_test[col].astype('category').cat.codes.replace(-1, np.nan)

# Aplicar transform al conjunto de test con el imputador ya ajustado (¡No hacer fit!)
location_data_imputed_test = knn_imputer.transform(location_data_test)

# Convertir los resultados imputados a un DataFrame
location_data_imputed_df_test = pd.DataFrame(location_data_imputed_test, columns=geo_cols + coordinate_cols)

# Volver a mapear los valores imputados a las categorías originales
for col in geo_cols:
    location_data_imputed_df_test[col] = location_data_imputed_df_test[col].round().astype(int).replace({-1: np.nan})
    location_data_imputed_df_test[col] = location_data_imputed_df_test[col].astype('category')

# Actualizar el conjunto de test con los valores imputados
for col in geo_cols:
    df_test[col] = location_data_imputed_df_test[col]

# Aplicar Target Encoding usando los valores de entrenamiento
for col in ['neighbourhood', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'market', 'smart_location', 'country', 'country_code']:
    if col in mean_map:
        df_test[col] = df_test[col].map(mean_map.get(col, np.nan))


# Asegurar que 'country_code' es de tipo cadena para que 'XX' sea compatible
df_test['country_code'] = df_test['country_code'].astype(str)

# Imputar valores nulos en 'country_code' con la moda o 'XX' si no hay moda
df_test['country_code'] = df_test['country_code'].fillna(df_test['country_code'].mode().iloc[0] if not df_test['country_code'].mode().empty else 'XX')



# Imputar 'country' utilizando la moda basada en grupos de coordenadas cercanas en test
df_test['country'] = df_test.groupby(['latitude', 'longitude'])['country'].transform(lambda x: x.fillna(x.mode().iloc[0]) if not x.mode().empty else x)

# Imputar 'neighbourhood_group_cleansed' y 'neighbourhood_cleansed' utilizando la moda de 'neighbourhood' en test
df_test['neighbourhood_cleansed'] = df_test.groupby('neighbourhood', observed=True)['neighbourhood_cleansed'].transform(lambda x: x.fillna(x.mode().iloc[0]) if not x.mode().empty else x)

# Si persisten valores nulos en 'neighbourhood_cleansed', imputarlos con la moda general
df_test['neighbourhood_cleansed'] = df_test['neighbourhood_cleansed'].fillna(df_test['neighbourhood_cleansed'].mode().iloc[0])
df_test['neighbourhood_group_cleansed'] = df_test.groupby('neighbourhood', observed=False)['neighbourhood_group_cleansed'].transform(lambda x: x.fillna(x.mode().iloc[0]) if not x.mode().empty else x)

# Imputar 'market' utilizando una combinación de 'city', 'state', y 'zipcode' en test
df_test['market'] = df_test.groupby(['city', 'state', 'zipcode'], observed=False)['market'].transform(lambda x: x.fillna(x.mode().iloc[0]) if not x.mode().empty else x)

# Para cualquier valor que aún sea nulo después de la imputación grupal, imputar con la moda general
cols_to_impute_general = ['country', 'neighbourhood_group_cleansed', 'market', 'smart_location', 'country_code']
for col in cols_to_impute_general:
    df_test[col] = df_test[col].fillna(df_test[col].mode().iloc[0])

# Paso 5: Imputar días desde las reseñas
days_max_value = max(df_test['days_since_first_review'].max(), df_test['days_since_last_review'].max()) + 1
df_test['days_since_first_review'] = df_test.apply(lambda x: days_max_value if x['number_of_reviews'] == 0 and pd.isna(x['days_since_first_review']) else x['days_since_first_review'], axis=1)
df_test['days_since_last_review'] = df_test.apply(lambda x: days_max_value if x['number_of_reviews'] == 0 and pd.isna(x['days_since_last_review']) else x['days_since_last_review'], axis=1)

df_test['days_since_first_review'] = df_test['days_since_first_review'].fillna(df_test[df_test['number_of_reviews'] > 0]['days_since_first_review'].median())
df_test['days_since_last_review'] = df_test['days_since_last_review'].fillna(df_test[df_test['number_of_reviews'] > 0]['days_since_last_review'].median())

# Paso 6: Imputar 'host_total_listings_count' con la mediana de train
df_test['host_total_listings_count'] = df_test.groupby('property_type')['host_total_listings_count'].transform(lambda x: x.fillna(x.median()))
df_test['host_total_listings_count'] = df_test['host_total_listings_count'].fillna(df_test['host_total_listings_count'].median())

# Paso 7: One-Hot Encoding para las categorías que usaste en entrenamiento
categorical_features = ['cancellation_policy']
df_test_encoded = pd.get_dummies(df_test, columns=categorical_features, drop_first=True)

# Seleccionar las columnas relevantes para la imputación
columns_to_impute = ['bathrooms', 'bedrooms', 'beds']
features_for_knn = ['property_type', 'square_meters', 'accommodates', 'room_type_private_room', 'room_type_shared_room', 'bed_type_couch', 'bed_type_futon', 'bed_type_pullout_sofa', 'bed_type_real_bed'] + columns_to_impute

# Crear una copia del dataset para trabajar en la imputación
knn_data = df_bnb[features_for_knn].copy()

# Convertir las columnas categóricas a numéricas
knn_data = pd.get_dummies(knn_data, drop_first=True)

# Escalar los datos
scaler = StandardScaler()
knn_data_scaled = scaler.transform(knn_data)

# Aplicar KNN Imputation
knn_imputer = KNNImputer(n_neighbors=5)
knn_data_imputed = knn_imputer.fit_transform(knn_data_scaled)

# Convertir los datos imputados de vuelta a un DataFrame
knn_data_imputed_df = pd.DataFrame(knn_data_imputed, columns=knn_data.columns)

# Actualizar las columnas imputadas en el dataset original
for col in columns_to_impute:
    df_test[col] = knn_data_imputed_df[col].round().astype(int)

# Cargar las columnas de train guardadas previamente
train_columns = joblib.load('train_columns.joblib')

# Asegurar que las columnas de test coincidan con las de train
missing_cols = [col for col in train_columns if col not in df_test_encoded.columns]

# Crear un DataFrame con las columnas faltantes llenas de ceros
missing_df = pd.DataFrame(0, index=df_test_encoded.index, columns=missing_cols)

# Concatenar las columnas faltantes con df_test_encoded de una sola vez
df_test_encoded = pd.concat([df_test_encoded, missing_df], axis=1)

# Eliminar columnas adicionales que están en test pero no en train
extra_cols = [col for col in df_test_encoded.columns if col not in train_columns]
df_test_encoded = df_test_encoded.drop(columns=extra_cols)

# Columnas categóricas para Target Encoding, incluyendo las categorías de localización relevantes (sin 'street')
categorical_cols = [
    'neighbourhood', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 
    'market', 'smart_location', 'country_code', 'country', 'country_code'
]

# Realizar Target Encoding en los datos de entrenamiento
mean_map = {}
for col in categorical_cols:
    # Calcular la media del target (price) por cada categoría
    mean = df_test.groupby(col)['price'].mean()
    # Reemplazar cada valor categórico con la media calculada
    df_bnb[col] = df_test[col].map(mean)
    # Guardar el mapeo para futura referencia si se necesita
    mean_map[col] = mean

# Target Encoding con suavizado para 'Property Type'
property_col = 'property_type'

# Parámetros de suavizado
min_samples = 100  # Número mínimo de muestras para aplicar el promedio del target
smoothing = 10     # Factor de suavizado

# Calcular la media general del precio
global_mean = df_test['price'].mean()

# Calcular la media por categoría y el tamaño de cada grupo
mean_per_category = df_test.groupby(property_col)['price'].mean()
counts_per_category = df_test.groupby(property_col)['price'].count()

# Aplicar suavizado para evitar overfitting
df_test[property_col + '_encoded'] = df_test[property_col].map(
    lambda x: (counts_per_category[x] * mean_per_category[x] + smoothing * global_mean) /
              (counts_per_category[x] + smoothing) if x in mean_per_category else global_mean
)

# Eliminar la columna original para evitar duplicación
df_test = df_test.drop(columns=[property_col])

In [ ]:
# Verificar categorías únicas en train y test
for col in ['neighbourhood', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'market', 'smart_location', 'country', 'country_code']:
    train_unique = set(df_bnb[col].unique())
    test_unique = set(df_test[col].unique())
    
    # Categorías en test que no están en train
    missing_categories = test_unique - train_unique
    print(f"Categorías en test pero no en train para {col}: {missing_categories}")


In [ ]:
# Verificar si hay columnas no numéricas
non_numeric_cols = df_test_encoded.select_dtypes(include=['object']).columns
print(f"Columnas no numéricas en test: {non_numeric_cols}")


In [ ]:
# Verificar si hay otras columnas no numéricas en test
non_numeric_cols = df_test_encoded.select_dtypes(include=['object']).columns
print(f"Columnas no numéricas en test: {non_numeric_cols}")


In [ ]:
# Verificar si hay valores nulos en el conjunto de test
missing_values = df_test_encoded.isnull().sum()
print(missing_values[missing_values > 0])


Ahora preparamos datos para sklearn

In [112]:
from sklearn import preprocessing

# Dataset de train
data_train = df_bnb.values
y_train = data_train[:,0:1]     # nos quedamos con la 1ª columna, price
X_train = data_train[:,1:]      # nos quedamos con el resto

# Dataset de test
data_test = df_test.values
y_test = data_test[:,0:1]     # nos quedamos con la 1ª columna, price
X_test = data_test[:,1:]      # nos quedamos con el resto

In [ ]:
# Escalamos (con los datos de train)
scaler = preprocessing.StandardScaler().fit(X_train)
XtrainScaled = scaler.transform(X_train)

# recordad que esta normalización/escalado la realizo con el scaler anterior, basado en los datos de training!
XtestScaled = scaler.transform(X_test) 